"""alter serving deploy platform type

Revision ID: 0166249ad82d
Revises: 1c4c6f630642
Create Date: 2022-09-21 10:34:16.507923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0166249ad82d'
down_revision = '1c4c6f630642'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serving_deployments_v2', 'deploy_platform',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_comment='deploy platform. None means inside this platform',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('serving_deployments_v2', 'deploy_platform',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_comment='deploy platform. None means inside this platform',
               existing_nullable=True)
    # ### end Alembic commands ###
