"""Change DataBatch details from blob to mediumblob

Revision ID: 1122cc13ef9d
Revises: 3433f0ca2193
Create Date: 2021-11-22 14:59:00.406242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1122cc13ef9d'
down_revision = '3433f0ca2193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_batches_v2', 'details', existing_type=sa.LargeBinary(), type_=sa.LargeBinary(16777215), comment='details')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_batches_v2', 'details', existing_type=sa.LargeBinary(16777215), type_=mysql.BLOB)
    # ### end Alembic commands ###
