"""empty message

Revision ID: 1b5c86643811
Revises: 5a580877595d
Create Date: 2021-03-29 23:08:05.126889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5c86643811'
down_revision = '5a580877595d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_v2', sa.Column('editor_info', sa.LargeBinary(length=16777215), nullable=True, comment='editor_info'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'editor_info')
    # ### end Alembic commands ###
