"""Remove sql enum constraint

Revision ID: 1d646afb8846
Revises: 5810b21435ae
Create Date: 2021-06-22 14:56:58.517358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d646afb8846'
down_revision = '5810b21435ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    version = bind.execute('select version()')
    # 'drop check' is invalid if mysql version is less than 8
    if version is not None and version.fetchall()[0][0] > '8.0.0':
        op.execute('ALTER TABLE job_v2 drop check jobtype')
        op.execute('ALTER TABLE users_v2 drop check role')
        op.execute('ALTER TABLE users_v2 drop check state')
        op.execute('ALTER TABLE datasets_v2 drop check datasettype')
        op.execute('ALTER TABLE data_batches_v2 drop check batchstate')
        op.execute('ALTER TABLE workflow_v2 drop check recurtype')
        op.execute('ALTER TABLE workflow_v2 drop check workflow_state')
        op.execute('ALTER TABLE workflow_v2 drop check workflow_target_state')
        op.execute('ALTER TABLE workflow_v2 drop check transactionstate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    # DO NOT DOWNGRADE THIS VERSION!!!!
    # ### end Alembic commands ###
