"""adds cascade columns for settings

Revision ID: 263717c82a6a
Revises: 9a9b20f3804e
Create Date: 2021-08-02 21:54:54.421093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263717c82a6a'
down_revision = '9a9b20f3804e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'))
    op.add_column('settings_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings_v2', 'updated_at')
    op.drop_column('settings_v2', 'created_at')
    # ### end Alembic commands ###
