"""add kind in workflow_templates

Revision ID: 27a868485bf7
Revises: 7efe1ea47186
Create Date: 2021-04-28 16:29:41.898112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27a868485bf7'
down_revision = '7efe1ea47186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_v2', sa.Column('kind', sa.Integer(), nullable=True, comment='template kind'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'kind')
    # ### end Alembic commands ###
