"""add model serving two db tables

Revision ID: 2d9c3afaa7fe
Revises: 7cf3168e68fb
Create Date: 2021-09-25 20:44:13.208086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9c3afaa7fe'
down_revision = '7cf3168e68fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serving_deployments_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='project id'),
    sa.Column('deployment_name', sa.String(length=255), nullable=True, comment='deployment name'),
    sa.Column('rsc', sa.String(length=255), nullable=True, comment='resource'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='endpoint'),
    sa.Column('status', sa.Enum('UNAVAILABLE', 'AVAILABLE', name='servingdeploymentstatus', native_enum=False, length=64, create_constraint=False), nullable=True, comment='status'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='created_at'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra'),
    sa.PrimaryKeyConstraint('id'),
    comment='serving deployments in webconsole',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_table('serving_models_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='project id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('serving_deployment_id', sa.Integer(), nullable=True, comment='serving deployment db id'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='model id'),
    sa.Column('model_type', sa.Enum('UNSPECIFIED', 'NN_MODEL', 'TREE_MODEL', name='modeltype', native_enum=False, length=64, create_constraint=False), nullable=True, comment='model type'),
    sa.Column('model_path', sa.String(length=255), nullable=True, comment="model's path"),
    sa.Column('signature', sa.Text(), nullable=True, comment='model signature'),
    sa.Column('status', sa.Enum('UNKNOWN', 'LOADING', 'AVAILABLE', 'UNLOADING', name='servingmodelstatus', native_enum=False, length=64, create_constraint=False), nullable=True, comment='status'),
    sa.Column('endpoint', sa.String(length=255), nullable=True, comment='endpoint'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='created_at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='updated_at'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uniq_name'),
    comment='serving models',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serving_models_v2')
    op.drop_table('serving_deployments_v2')
    # ### end Alembic commands ###
