"""change_workflow_name_unique

Revision ID: 2d9ee2c8ac6e
Revises: d6b3fa7f23a6
Create Date: 2022-03-24 15:16:31.251607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d9ee2c8ac6e'
down_revision = 'd6b3fa7f23a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_name_in_project', 'workflow_v2', ['project_id', 'name'])
    op.drop_index('uniq_name', table_name='workflow_v2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uniq_name', 'workflow_v2', ['name'], unique=True)
    op.drop_constraint('uniq_name_in_project', 'workflow_v2', type_='unique')
    # ### end Alembic commands ###
