"""[batches_v2]: make event time optional

Revision ID: 351844c6fd92
Revises: 8bde5b704062
Create Date: 2022-06-27 05:26:34.313560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '351844c6fd92'
down_revision = '7549e6d94cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_batches_v2',
                    'event_time',
                    existing_type=mysql.TIMESTAMP(),
                    nullable=True,
                    existing_comment='event_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_batches_v2',
                    'event_time',
                    existing_type=mysql.TIMESTAMP(),
                    nullable=False,
                    existing_comment='event_time')
    # ### end Alembic commands ###
