"""add tpl pure domain name

Revision ID: 368b8bd6d559
Revises: c01cdd2253e4
Create Date: 2022-09-28 17:13:13.883713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '368b8bd6d559'
down_revision = 'c01cdd2253e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_v2', sa.Column('coordinator_pure_domain_name', sa.String(length=255), nullable=True, comment='name of the coordinator'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'coordinator_pure_domain_name')
    # ### end Alembic commands ###
