"""refactor_models_and_model_groups_table

Revision ID: 3b4198785f3d
Revises: 9d3a1d2393e7
Create Date: 2021-09-24 15:16:05.800630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3b4198785f3d'
down_revision = '9d3a1d2393e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('cmt', sa.Text(), nullable=True, comment='comment'))
    op.add_column('model_groups_v2', sa.Column('project_id', sa.Integer(), nullable=True, comment='project_id'))
    op.create_unique_constraint('uniq_name', 'model_groups_v2', ['name'])
    op.add_column('model_jobs_v2', sa.Column('favorite', sa.Boolean(), nullable=True, comment='favorite'))
    op.add_column('model_jobs_v2', sa.Column('model_job_type', sa.Enum('UNSPECIFIED', 'NN_TRAINING', 'NN_EVALUATION', 'NN_PREDICTION', 'TREE_TRAINING', 'TREE_EVALUATION', 'TREE_PREDICTION', name='modeljobtype', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='type'))
    op.create_table_comment(
        'model_jobs_v2',
        'model_jobs_v2',
        existing_comment='model',
        schema=None
    )
    op.drop_column('model_jobs_v2', 'type')
    op.add_column('models_v2', sa.Column('cmt', sa.Text(), nullable=True, comment='comment'))
    op.add_column('models_v2', sa.Column('favorite', sa.Boolean(), nullable=True, comment='favorite model'))
    op.add_column('models_v2', sa.Column('job_id', sa.Integer(), nullable=True, comment='job id'))
    op.add_column('models_v2', sa.Column('model_job_id', sa.Integer(), nullable=True, comment='model job id'))
    op.add_column('models_v2', sa.Column('model_type', sa.Enum('UNSPECIFIED', 'NN_MODEL', 'TREE_MODEL', name='modeltype', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='type'))
    op.add_column('models_v2', sa.Column('model_path', sa.String(length=512), nullable=True, comment='model path'))
    op.add_column('models_v2', sa.Column('project_id', sa.Integer(), nullable=True, comment='project_id'))
    op.add_column('models_v2', sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'))
    op.drop_index('idx_job_name', table_name='models_v2')
    op.drop_index('uniq_job_name', table_name='models_v2')
    op.create_unique_constraint('uniq_name', 'models_v2', ['name'])
    op.create_unique_constraint('uniq_uuid', 'models_v2', ['uuid'])
    op.create_table_comment(
        'models_v2',
        'models_v2',
        existing_comment='model',
        schema=None
    )
    op.drop_column('models_v2', 'params')
    op.drop_column('models_v2', 'extra')
    op.drop_column('models_v2', 'metrics')
    op.drop_column('models_v2', 'type')
    op.drop_column('models_v2', 'state')
    op.drop_column('models_v2', 'parent_id')
    op.drop_column('models_v2', 'job_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_v2', sa.Column('job_name', mysql.VARCHAR(length=255), nullable=True, comment='job_name'))
    op.add_column('models_v2', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='parent_id'))
    op.add_column('models_v2', sa.Column('state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='state'))
    op.add_column('models_v2', sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='type'))
    op.add_column('models_v2', sa.Column('metrics', mysql.TEXT(), nullable=True, comment='metrics'))
    op.add_column('models_v2', sa.Column('extra', mysql.TEXT(), nullable=True, comment='extra'))
    op.add_column('models_v2', sa.Column('params', mysql.TEXT(), nullable=True, comment='params'))
    op.create_table_comment(
        'models_v2',
        'model',
        existing_comment='models_v2',
        schema=None
    )
    op.drop_constraint('uniq_uuid', 'models_v2', type_='unique')
    op.drop_constraint('uniq_name', 'models_v2', type_='unique')
    op.create_index('uniq_job_name', 'models_v2', ['job_name'], unique=True)
    op.create_index('idx_job_name', 'models_v2', ['job_name'], unique=False)
    op.drop_column('models_v2', 'uuid')
    op.drop_column('models_v2', 'project_id')
    op.drop_column('models_v2', 'model_path')
    op.drop_column('models_v2', 'model_type')
    op.drop_column('models_v2', 'model_job_id')
    op.drop_column('models_v2', 'job_id')
    op.drop_column('models_v2', 'favorite')
    op.drop_column('models_v2', 'cmt')
    op.add_column('model_jobs_v2', sa.Column('type', mysql.VARCHAR(length=32), nullable=True, comment='type'))
    op.create_table_comment(
        'model_jobs_v2',
        'model',
        existing_comment='model_jobs_v2',
        schema=None
    )
    op.drop_column('model_jobs_v2', 'model_job_type')
    op.drop_column('model_jobs_v2', 'favorite')
    op.drop_constraint('uniq_name', 'model_groups_v2', type_='unique')
    op.drop_column('model_groups_v2', 'project_id')
    op.drop_column('model_groups_v2', 'cmt')
    # ### end Alembic commands ###
