"""add projector creator

Revision ID: 3cec138fc005
Revises: 1122cc13ef9d
Create Date: 2021-12-01 17:26:22.038103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cec138fc005'
down_revision = '1122cc13ef9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_v2', sa.Column('creator', sa.String(length=255), nullable=True, comment='creator'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_v2', 'creator')
    # ### end Alembic commands ###
