"""add algorithm uuid

Revision ID: 40569c37cb87
Revises: 2d9ee2c8ac6e
Create Date: 2022-03-30 20:56:11.940565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40569c37cb87'
down_revision = '2d9ee2c8ac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm_projects_v2', sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'))
    op.create_unique_constraint('uniq_uuid', 'algorithm_projects_v2', ['uuid'])
    op.add_column('algorithms_v2', sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'))
    op.create_unique_constraint('uniq_uuid', 'algorithms_v2', ['uuid'])
    op.add_column('pending_algorithms_v2', sa.Column('algorithm_uuid', sa.String(length=64), nullable=True, comment='algorithm uuid'))
    op.add_column('pending_algorithms_v2', sa.Column('algorithm_project_uuid', sa.String(length=64), nullable=True, comment='algorithm project uuid'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_algorithms_v2', 'algorithm_project_uuid')
    op.drop_column('pending_algorithms_v2', 'algorithm_uuid')
    op.drop_constraint('uniq_uuid', 'algorithms_v2', type_='unique')
    op.drop_column('algorithms_v2', 'uuid')
    op.drop_constraint('uniq_uuid', 'algorithm_projects_v2', type_='unique')
    op.drop_column('algorithm_projects_v2', 'uuid')
    # ### end Alembic commands ###
