"""add spark info in jobs table

Revision ID: 42fc79d5a917
Revises: b3290c1bf67a
Create Date: 2021-06-15 12:42:08.060464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42fc79d5a917'
down_revision = 'b3290c1bf67a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_groups_v2',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created_at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated_at'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted_at'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra'),
    sa.PrimaryKeyConstraint('id'),
    comment='model_groups_v2',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.add_column('job_v2', sa.Column('sparkapp_snapshot', sa.Text(length=16777215), nullable=True, comment='sparkapp snapshot'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_v2', 'sparkapp_snapshot')
    op.drop_table('model_groups_v2')
    # ### end Alembic commands ###
