"""participant add migrations

Revision ID: 4d281f0968fa
Revises: 45362e49da14
Create Date: 2022-11-23 08:49:38.983606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d281f0968fa'
down_revision = '45362e49da14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants_v2', sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'))
    op.add_column('participants_v2', sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='review ticket status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants_v2', 'ticket_status')
    op.drop_column('participants_v2', 'ticket_uuid')
    # ### end Alembic commands ###
