"""add_version_in_model_job_and_group

Revision ID: 539df90fe13e
Revises: 61f65a987341
Create Date: 2022-02-14 19:54:39.272811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539df90fe13e'
down_revision = '61f65a987341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('latest_version', sa.Integer(), nullable=True, comment='latest version'))
    op.add_column('model_jobs_v2', sa.Column('version', sa.Integer(), nullable=True, comment='version'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs_v2', 'version')
    op.drop_column('model_groups_v2', 'latest_version')
    # ### end Alembic commands ###
