"""update event user_id to ullable

Revision ID: 554fd3c48986
Revises: c038f88210a7
Create Date: 2022-08-19 16:41:53.125112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '554fd3c48986'
down_revision = 'c038f88210a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events_v2', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_comment='the ID of the user who triggered the event')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events_v2', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_comment='the ID of the user who triggered the event')
    # ### end Alembic commands ###
