"""add_algorithm_publish_status_and_change_project_to_release

Revision ID: 5f322c9d67ea
Revises: a5d59be86a15
Create Date: 2022-07-25 11:32:52.479087

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f322c9d67ea'
down_revision = 'a5d59be86a15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('algorithm_projects_v2', 'publish_status',
               type_=sa.Enum('UNPUBLISHED', 'PUBLISHED', 'UNRELEASED', 'RELEASED', name='publish_status', native_enum=False, create_constraint=False, length=32),
               comment='release status',
               existing_comment='publish status',
               existing_nullable=True)
    op.add_column('algorithms_v2', sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'))
    op.add_column('algorithms_v2', sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='review ticket status'))
    op.add_column('algorithms_v2', sa.Column('publish_status', sa.Enum('UNPUBLISHED', 'PUBLISHED', name='publishstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='publish status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithms_v2', 'publish_status')
    op.drop_column('algorithms_v2', 'ticket_status')
    op.drop_column('algorithms_v2', 'ticket_uuid')
    op.alter_column('algorithm_projects_v2', 'publish_status',
               type_=sa.Enum('UNPUBLISHED', 'PUBLISHED', name='publish_status', native_enum=False, create_constraint=False, length=32),
               comment='publish status',
               existing_comment='release status',
               existing_nullable=True)
    # ### end Alembic commands ###
