"""change composer runner pipeline size

Revision ID: 6ffeddd94543
Revises: 959e368487bd
Create Date: 2021-12-14 10:36:29.518893

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '6ffeddd94543'
down_revision = '959e368487bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_runner_v2', 'pipeline',
               existing_type=sa.Text(),
               type_=sa.Text(16777215),
               nullable=False, 
               comment='pipeline from scheduler item')
    op.alter_column('scheduler_runner_v2', 'context',
               existing_type=sa.Text(),
               type_=sa.Text(16777215),
               nullable=False, 
               comment='context')
    op.alter_column('scheduler_item_v2', 'pipeline',
               existing_type=sa.Text(16777215),
               nullable=False,
               existing_comment='pipeline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_runner_v2', 'pipeline',
               existing_type=sa.Text(16777215),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('scheduler_runner_v2', 'context',
               existing_type=sa.Text(16777215),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('scheduler_item_v2', 'pipeline',
               existing_type=sa.Text(16777215),
               nullable=True,
               existing_comment='pipeline')
    # ### end Alembic commands ###
