"""create tee tables

Revision ID: 721609ac068b
Revises: 4889e8718b51
Create Date: 2022-08-26 20:17:49.442756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721609ac068b'
down_revision = '4889e8718b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trusted_job_groups_v2',
    sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'),
    sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='review ticket status'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'),
    sa.Column('latest_version', sa.Integer(), nullable=True, comment='latest version'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment of trusted job group'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='project id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'),
    sa.Column('creator_username', sa.String(length=255), nullable=True, comment='creator username'),
    sa.Column('coordinator_id', sa.Integer(), nullable=True, comment='coordinator participant id'),
    sa.Column('analyzer_id', sa.Integer(), nullable=True, comment='analyzer participant id'),
    sa.Column('status', sa.Enum('PENDING', 'FAILED', 'SUCCEEDED', name='groupcreatestatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='create state'),
    sa.Column('auth_status', sa.Enum('PENDING', 'AUTHORIZED', name='authstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='auth status'),
    sa.Column('unauth_participant_ids', sa.Text(), nullable=True, comment='unauth participant ids'),
    sa.Column('algorithm_id', sa.Integer(), nullable=True, comment='algorithm id'),
    sa.Column('rsc', sa.String(length=255), nullable=True, comment='resource'),
    sa.Column('dataset_id', sa.Integer(), nullable=True, comment='dataset id'),
    sa.Column('participant_datasets', sa.Text(), nullable=True, comment='list of participant-to-dataset mapping'),
    sa.PrimaryKeyConstraint('id'),
    comment='trusted_job_groups_v2',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_trusted_group_name', 'trusted_job_groups_v2', ['name'], unique=False)
    op.create_index('idx_trusted_group_project_id', 'trusted_job_groups_v2', ['project_id'], unique=False)
    op.create_table('trusted_jobs_v2',
    sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'),
    sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='review ticket status'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('trusted_job_type', sa.Enum('ANALYZE', 'EXPORT', name='trustedjobtype', native_enum=False, create_constraint=False, length=32), nullable=True, comment='trusted job type'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='job id'),
    sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'),
    sa.Column('version', sa.Integer(), nullable=True, comment='version'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment of trusted job'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='project id'),
    sa.Column('trusted_job_group_id', sa.Integer(), nullable=True, comment='trusted job group id'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='started_at'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='finished_at'),
    sa.Column('status', sa.Enum('NEW', 'CREATED', 'PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'STOPPED', name='trustedjobstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='trusted job status'),
    sa.Column('auth_status', sa.Enum('PENDING', 'AUTHORIZED', name='authstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='auth status'),
    sa.Column('algorithm_id', sa.Integer(), nullable=True, comment='algorithm id'),
    sa.Column('rsc', sa.String(length=255), nullable=True, comment='resource'),
    sa.Column('dataset_job_id', sa.Integer(), nullable=True, comment='dataset job id'),
    sa.Column('result_key', sa.Text(), nullable=True, comment='result key'),
    sa.PrimaryKeyConstraint('id'),
    comment='trusted_jobs_v2',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_trusted_name', 'trusted_jobs_v2', ['name'], unique=False)
    op.create_index('idx_trusted_project_id', 'trusted_jobs_v2', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trusted_project_id', table_name='trusted_jobs_v2')
    op.drop_index('idx_trusted_name', table_name='trusted_jobs_v2')
    op.drop_table('trusted_jobs_v2')
    op.drop_index('idx_trusted_group_project_id', table_name='trusted_job_groups_v2')
    op.drop_index('idx_trusted_group_name', table_name='trusted_job_groups_v2')
    op.drop_table('trusted_job_groups_v2')
    # ### end Alembic commands ###
