"""add_favour

Revision ID: 72ce71d23931
Revises: 3e5b9367ced3
Create Date: 2022-03-04 17:34:18.310004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ce71d23931'
down_revision = '3e5b9367ced3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_v2', sa.Column('favour', sa.Boolean(), nullable=True, comment='favour'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_v2', 'favour')
    # ### end Alembic commands ###
