"""add_creator_and_coordinator_id_in_model

Revision ID: 8037467dca2c
Revises: 72ce71d23931
Create Date: 2022-03-08 15:15:51.601676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8037467dca2c'
down_revision = '72ce71d23931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('coordinator_id', sa.Integer(), nullable=True, comment='coordinator participant id'))
    op.add_column('model_groups_v2', sa.Column('creator_username', sa.String(length=255), nullable=True, comment='creator username'))
    op.add_column('model_jobs_v2', sa.Column('coordinator_id', sa.Integer(), nullable=True, comment='coordinator participant id'))
    op.add_column('model_jobs_v2', sa.Column('creator_username', sa.String(length=255), nullable=True, comment='creator username'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs_v2', 'creator_username')
    op.drop_column('model_jobs_v2', 'coordinator_id')
    op.drop_column('model_groups_v2', 'creator_username')
    op.drop_column('model_groups_v2', 'coordinator_id')
    # ### end Alembic commands ###
