"""add cleanups_v2 schema

Revision ID: 815ae1dcd9db
Revises: 40569c37cb87
Create Date: 2022-04-08 18:48:44.456038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815ae1dcd9db'
down_revision = '40569c37cb87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanups_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('state', sa.Enum('WAITING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='cleanupstate', native_enum=False, length=64, create_constraint=False), nullable=True, comment='state'),
    sa.Column('target_start_at', sa.DateTime(timezone=True), nullable=True, comment='target_start_at'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='completed_at'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='resource_id'),
    sa.Column('resource_type', sa.Enum('DATASET', 'MODEL', 'ALGORITHM', 'NO_RESOURCE', name='resourcetype', native_enum=False, length=64, create_constraint=False), nullable=True, comment='resource_type'),
    sa.Column('payload', sa.Text(), nullable=True, comment='the underlying resources that need to be cleaned up'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created_at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated_at'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleanups_v2')
    # ### end Alembic commands ###
