"""add_algorithm_type_to_model_job

Revision ID: 8259e68074a0
Revises: 1e882d34c760
Create Date: 2022-01-07 17:01:19.349467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8259e68074a0'
down_revision = '1e882d34c760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_jobs_v2', sa.Column('algorithm_id', sa.Integer(), nullable=True, comment='algorithm id'))
    op.add_column('model_jobs_v2', sa.Column('algorithm_type', sa.Enum('UNSPECIFIED', 'NN_LOCAL', 'NN_HORIZONTAL', 'NN_VERTICAL', 'TREE_VERTICAL', name='algorithmtype', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='algorithm type'))
    op.drop_column('model_jobs_v2', 'code_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_jobs_v2', sa.Column('code_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='code_id'))
    op.drop_column('model_jobs_v2', 'algorithm_type')
    op.drop_column('model_jobs_v2', 'algorithm_id')
    # ### end Alembic commands ###
