"""add_pending_project

Revision ID: 87c0ca7b825a
Revises: 721609ac068b
Create Date: 2022-09-14 21:27:06.438325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87c0ca7b825a'
down_revision = '721609ac068b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_projects_v2',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted time'),
    sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'),
    sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, length=32, create_constraint=False), server_default='APPROVED', nullable=True, comment='review ticket status'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'),
    sa.Column('config', sa.Text(), nullable=True, comment='config'),
    sa.Column('state', sa.Enum('PENDING', 'ACCEPTED', 'FAILED', 'CLOSED', name='pendingprojectstate', native_enum=False, length=32, create_constraint=False), nullable=False, comment='pending project stage state'),
    sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'),
    sa.Column('role', sa.Enum('COORDINATOR', 'PARTICIPANT', name='projectrole', native_enum=False, length=32, create_constraint=False), nullable=False, comment='pending project role'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment'),
    sa.Column('creator_username', sa.String(length=255), nullable=True, comment='creator'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'),
    sa.PrimaryKeyConstraint('id'),
    comment='This is webconsole pending_project table',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.add_column('projects_v2', sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'))
    op.add_column('projects_v2', sa.Column('role', sa.Enum('COORDINATOR', 'PARTICIPANT', name='projectrole', native_enum=False, length=32, create_constraint=False), nullable=True, comment='pending project role'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects_v2', 'role')
    op.drop_column('projects_v2', 'participants_info')
    op.drop_table('pending_projects_v2')
    # ### end Alembic commands ###
