"""Remove certificate row

Revision ID: 8b179c0111a8
Revises: c06f66dbebc1
Create Date: 2021-10-21 11:50:53.805840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b179c0111a8'
down_revision = 'c06f66dbebc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants_v2', 'certificates')
    op.drop_column('projects_v2', 'certificate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects_v2', sa.Column('certificate', sa.BLOB(), nullable=True, comment='certificate'))
    op.add_column('participants_v2', sa.Column('certificates', sa.BLOB(), nullable=True, comment='certificates'))
    # ### end Alembic commands ###
