"""add_status_index_for_composer

Revision ID: 8bde5b704062
Revises: 0f24b50d4077
Create Date: 2022-06-15 11:30:13.769478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bde5b704062'
down_revision = '0f24b50d4077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_item_status', 'scheduler_item_v2', ['status'], unique=False)
    op.create_index('idx_runner_item_id', 'scheduler_runner_v2', ['item_id'], unique=False)
    op.create_index('idx_runner_status', 'scheduler_runner_v2', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_runner_status', table_name='scheduler_runner_v2')
    op.drop_index('idx_runner_item_id', table_name='scheduler_runner_v2')
    op.drop_index('idx_item_status', table_name='scheduler_item_v2')
    # ### end Alembic commands ###
