"""model_job_add_auth_frontend_status

Revision ID: 8c2d01a90f9a
Revises: be2c1a6523cd
Create Date: 2022-12-30 13:27:00.549545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2d01a90f9a'
down_revision = 'be2c1a6523cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_jobs_v2', sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'))
    op.add_column('model_jobs_v2', sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, create_constraint=False, length=32), server_default='APPROVED', nullable=True, comment='review ticket status'))
    op.add_column('model_jobs_v2', sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'))
    op.add_column('model_jobs_v2', sa.Column('create_status', sa.Enum('PENDING', 'FAILED', 'SUCCEEDED', name='modeljobcreatestatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='create status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs_v2', 'create_status')
    op.drop_column('model_jobs_v2', 'participants_info')
    op.drop_column('model_jobs_v2', 'ticket_status')
    op.drop_column('model_jobs_v2', 'ticket_uuid')
    # ### end Alembic commands ###
