"""add_settings

Revision ID: 8f284fd1ddf5
Revises: 1d646afb8846
Create Date: 2021-06-28 17:05:08.826588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f284fd1ddf5'
down_revision = '1d646afb8846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings_v2',
    sa.Column('id', sa.Integer(), nullable=False, comment='id'),
    sa.Column('uniq_key', sa.String(length=255), nullable=False, comment='uniq_key'),
    sa.Column('value', sa.Text(), nullable=True, comment='value'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uniq_key', name='uniq_key'),
    comment='this is webconsole settings table',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings_v2')
    # ### end Alembic commands ###
