"""rename interval in scheduler_item

Revision ID: 8f4d3ac26935
Revises: ecfc6488a6c8
Create Date: 2021-04-14 18:45:59.695601

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f4d3ac26935'
down_revision = 'ecfc6488a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_item_v2', sa.Column('interval_time', sa.Integer(), nullable=False, comment='item run interval in second'))
    op.drop_column('scheduler_item_v2', 'interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_item_v2', sa.Column('interval', mysql.INTEGER(), autoincrement=False, nullable=False, comment='item run interval in second'))
    op.drop_column('scheduler_item_v2', 'interval_time')
    # ### end Alembic commands ###
