"""add_template_revision

Revision ID: 93c152b66879
Revises: a099147f5c69
Create Date: 2022-04-13 18:59:45.222007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c152b66879'
down_revision = 'a099147f5c69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_revisions_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('revision_index', sa.Integer(), nullable=True, comment='revision_index'),
    sa.Column('cmt', sa.String(length=255), nullable=True, comment='comment'),
    sa.Column('config', sa.LargeBinary(length=16777215), nullable=False, comment='config'),
    sa.Column('editor_info', sa.LargeBinary(length=16777215), nullable=True, comment='editor_info'),
    sa.Column('template_id', sa.Integer(), nullable=True, comment='template_id'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created_at'),
    sa.PrimaryKeyConstraint('id'),
    comment='workflow template revision',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_template_id', 'template_revisions_v2', ['template_id'], unique=False)
    op.add_column('workflow_v2', sa.Column('template_revision_id', sa.Integer(), nullable=True, comment='template_revision_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_v2', 'template_revision_id')
    op.drop_index('idx_template_id', table_name='template_revisions_v2')
    op.drop_table('template_revisions_v2')
    # ### end Alembic commands ###
