"""add_username_and_remove_creator_name

Revision ID: 93d756004237
Revises: 6ffeddd94543
Create Date: 2021-12-17 10:50:50.478584

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93d756004237'
down_revision = '6ffeddd94543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm_projects_v2', sa.Column('username', sa.String(length=255), nullable=True, comment='creator name'))
    op.drop_column('algorithm_projects_v2', 'creator_id')
    op.add_column('algorithms_v2', sa.Column('username', sa.String(length=255), nullable=True, comment='creator name'))
    op.drop_column('algorithms_v2', 'creator_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms_v2', sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='creator user id'))
    op.drop_column('algorithms_v2', 'username')
    op.add_column('algorithm_projects_v2', sa.Column('creator_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='creator user id'))
    op.drop_column('algorithm_projects_v2', 'username')
    # ### end Alembic commands ###
