"""change composer item pipeline size

Revision ID: 959e368487bd
Revises: 805f74540f34
Create Date: 2021-12-13 16:18:21.742170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '959e368487bd'
down_revision = '805f74540f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_item_v2', 'pipeline', existing_type=sa.Text(), type_=sa.Text(16777215), comment='pipeline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_item_v2', 'pipeline', existing_type=sa.Text(16777215), type_=sa.Text())
    # ### end Alembic commands ###
