"""tee export feat

Revision ID: 993096ed6fb3
Revises: 5082991f34c7
Create Date: 2022-10-20 19:48:28.048403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993096ed6fb3'
down_revision = '5082991f34c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_job_groups_v2', sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'))
    op.add_column('trusted_jobs_v2', sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'))
    op.add_column('trusted_jobs_v2', sa.Column('export_count', sa.Integer(), nullable=True, comment='export count'))
    op.add_column('trusted_jobs_v2', sa.Column('coordinator_id', sa.Integer(), nullable=True, comment='coordinator participant id'))
    op.add_column('trusted_jobs_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'))
    op.add_column('trusted_jobs_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trusted_jobs_v2', 'updated_at')
    op.drop_column('trusted_jobs_v2', 'created_at')
    op.drop_column('trusted_jobs_v2', 'coordinator_id')
    op.drop_column('trusted_jobs_v2', 'export_count')
    op.drop_column('trusted_jobs_v2', 'participants_info')
    op.drop_column('trusted_job_groups_v2', 'participants_info')
    # ### end Alembic commands ###
