"""refactor tee table

Revision ID: 9c321d108a16
Revises: a2311ac22777
Create Date: 2022-09-19 11:48:21.461194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c321d108a16'
down_revision = 'a2311ac22777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_job_groups_v2', sa.Column('algorithm_uuid', sa.String(length=64), nullable=True, comment='algorithm uuid'))
    op.drop_column('trusted_job_groups_v2', 'algorithm_id')
    op.add_column('trusted_jobs_v2', sa.Column('algorithm_uuid', sa.String(length=64), nullable=True, comment='algorithm uuid'))
    op.drop_column('trusted_jobs_v2', 'algorithm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trusted_jobs_v2', sa.Column('algorithm_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='algorithm id'))
    op.drop_column('trusted_jobs_v2', 'algorithm_uuid')
    op.add_column('trusted_job_groups_v2', sa.Column('algorithm_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='algorithm id'))
    op.drop_column('trusted_job_groups_v2', 'algorithm_uuid')
    # ### end Alembic commands ###
