"""add_model_jobs_table

Revision ID: 9d3a1d2393e7
Revises: a71c7db41200
Create Date: 2021-09-17 16:38:49.178642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3a1d2393e7'
down_revision = 'a71c7db41200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_jobs_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'),
    sa.Column('type', sa.Enum('UNSPECIFIED', 'NN_TRAINING', 'NN_EVALUATION', 'NN_PREDICTION', 'TREE_TRAINING', 'TREE_EVALUATION', 'TREE_PREDICTION', name='modeljobtype', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='type'),
    sa.Column('job_name', sa.String(length=255), nullable=True, comment='job_name'),
    sa.Column('job_id', sa.Integer(), nullable=True, comment='job id'),
    sa.Column('model_id', sa.Integer(), nullable=True, comment='model_id'),
    sa.Column('group_id', sa.Integer(), nullable=True, comment='group_id'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='project id'),
    sa.Column('workflow_id', sa.Integer(), nullable=True, comment='workflow id'),
    sa.Column('workflow_uuid', sa.String(length=64), nullable=True, comment='workflow uuid'),
    sa.Column('code_id', sa.Integer(), nullable=True, comment='code_id'),
    sa.Column('dataset_id', sa.Integer(), nullable=True, comment='dataset id'),
    sa.Column('intersection_dataset_id', sa.Integer(), nullable=True, comment='intersection dataset id'),
    sa.Column('params', sa.Text(), nullable=True, comment='params'),
    sa.Column('metrics', sa.Text(), nullable=True, comment='metrics'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created_at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated_at'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted_at'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', name='uniq_job_name'),
    comment='model',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_uuid', 'model_jobs_v2', ['uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_uuid', table_name='model_jobs_v2')
    op.drop_table('model_jobs_v2')
    # ### end Alembic commands ###
