"""add_cron_config_path_to_model

Revision ID: a099147f5c69
Revises: 5a3533682d9b
Create Date: 2022-04-15 18:42:10.001142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a099147f5c69'
down_revision = '5a3533682d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('cron_config', sa.String(length=255), nullable=True, comment='cron expression in UTC timezone'))
    op.add_column('model_groups_v2', sa.Column('fspath', sa.String(length=512), nullable=True, comment='model job group path'))
    op.add_column('model_jobs_v2', sa.Column('fspath', sa.String(length=512), nullable=True, comment='model job path'))
    op.add_column('models_v2', sa.Column('algorithm_type', sa.Enum('UNSPECIFIED', 'NN_LOCAL', 'NN_HORIZONTAL', 'NN_VERTICAL', 'TREE_VERTICAL', name='algorithmtype', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='algorithm type'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models_v2', 'algorithm_type')
    op.drop_column('model_jobs_v2', 'fspath')
    op.drop_column('model_groups_v2', 'fspath')
    op.drop_column('model_groups_v2', 'cron_config')
    # ### end Alembic commands ###
