"""combine_template_to_workflow

Revision ID: a0c688644b84
Revises: 8f284fd1ddf5
Create Date: 2021-07-07 18:33:14.574123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c688644b84'
down_revision = '8f284fd1ddf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_v2', sa.Column('editor_info', sa.LargeBinary(length=16777215), nullable=True, comment='editor_info'))
    op.add_column('workflow_v2', sa.Column('template_id', sa.Integer(), nullable=True, comment='template_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_v2', 'template_id')
    op.drop_column('workflow_v2', 'editor_info')
    # ### end Alembic commands ###
