"""removes workflow cron related fields

Revision ID: a1f5564f7d00
Revises: b809788132d0
Create Date: 2021-08-31 19:12:09.225018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1f5564f7d00'
down_revision = 'b809788132d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_v2', 'recur_at')
    op.drop_column('workflow_v2', 'recur_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_v2', sa.Column('recur_type', mysql.VARCHAR(length=11), nullable=True, comment='recur_type'))
    op.add_column('workflow_v2', sa.Column('recur_at', mysql.DATETIME(), nullable=True, comment='recur_at'))
    # ### end Alembic commands ###
