"""add ticket uuid and status

Revision ID: a2311ac22777
Revises: 87c0ca7b825a
Create Date: 2022-09-15 21:46:39.309346

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a2311ac22777'
down_revision = '87c0ca7b825a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets_v2', sa.Column('ticket_uuid', sa.String(length=255), nullable=True, comment='review ticket uuid, empty if review function is disable'))
    op.add_column('datasets_v2', sa.Column('ticket_status', sa.Enum('PENDING', 'APPROVED', 'DECLINED', name='ticketstatus', native_enum=False, length=32, create_constraint=False), server_default='APPROVED', nullable=True, comment='review ticket status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasets_v2', 'ticket_status')
    op.drop_column('datasets_v2', 'ticket_uuid')
    # ### end Alembic commands ###
