"""Initial migratio.

Revision ID: a36a936f2a1f
Revises: 93c152b66879
Create Date: 2022-04-20 19:14:07.916463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a36a936f2a1f'
down_revision = '93c152b66879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('template_revisions_v2', 'revision_index',
               existing_type=mysql.INTEGER(),
               comment='index for the same template',
               existing_comment='revision_index',
               existing_nullable=True)
    op.create_unique_constraint('uniq_revision_index_in_template', 'template_revisions_v2', ['template_id', 'revision_index'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_revision_index_in_template', 'template_revisions_v2', type_='unique')
    op.alter_column('template_revisions_v2', 'revision_index',
               existing_type=mysql.INTEGER(),
               comment='revision_index',
               existing_comment='index for the same template',
               existing_nullable=True)
    # ### end Alembic commands ###
