"""adds cron fields for composer

Revision ID: a71c7db41200
Revises: ed5502db91ec
Create Date: 2021-09-04 00:42:07.794368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a71c7db41200'
down_revision = 'ed5502db91ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_item_v2', sa.Column('cron_config', sa.String(length=255), nullable=True, comment='cron expression in UTC timezone'))
    op.drop_column('scheduler_item_v2', 'interval_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduler_item_v2', sa.Column('interval_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='item run interval in second'))
    op.drop_column('scheduler_item_v2', 'cron_config')
    # ### end Alembic commands ###
