"""add_completed_failed_jobstate

Revision ID: b3290c1bf67a
Revises: fe30109949aa
Create Date: 2021-06-15 01:41:14.660466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3290c1bf67a'
down_revision = 'fe30109949aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    version = bind.execute('select version()')
    # 'drop check' is invalid if mysql version is less than 8
    if version is not None and version.fetchall()[0][0] > '8.0.0':
        op.execute('ALTER TABLE job_v2 drop check jobstate')
    op.alter_column('job_v2', 'state', nullable=False, comment='state', type_=sa.Enum('INVALID', 'STOPPED', 'WAITING', 'STARTED', 'COMPLETED', 'FAILED', name='jobstate', native_enum=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    version = bind.execute('select version()')
    # 'drop check' is invalid if mysql version is less than 8
    if version is not None and version.fetchall()[0][0] > '8.0.0':
        op.execute('ALTER TABLE job_v2 drop check jobstate')
    op.alter_column('job_v2', 'state', nullable=False, comment='state', type_=sa.Enum('INVALID', 'STOPPED', 'WAITING', 'STARTED', name='jobstate', native_enum=False))
    # ### end Alembic commands ###
