"""rename path to fspath

Revision ID: b659f5763a27
Revises: a0c688644b84
Create Date: 2021-07-16 11:06:40.851662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b659f5763a27'
down_revision = 'a0c688644b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intersection_datasets_v2', sa.Column('fspath', sa.String(length=512), nullable=True, comment='dataset path'))
    op.drop_column('intersection_datasets_v2', 'path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intersection_datasets_v2', sa.Column('path', mysql.VARCHAR(length=512), nullable=True, comment='dataset path'))
    op.drop_column('intersection_datasets_v2', 'fspath')
    # ### end Alembic commands ###
