"""add cronjob config

Revision ID: b809788132d0
Revises: 263717c82a6a
Create Date: 2021-08-05 19:06:12.212366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b809788132d0'
down_revision = '263717c82a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_v2', sa.Column('cronjob_config', sa.Text(), nullable=True, comment='cronjob json string'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_v2', 'cronjob_config')
    # ### end Alembic commands ###
