"""update_algorithm_project_unique_constraint

Revision ID: be2c1a6523cd
Revises: 4d281f0968fa
Create Date: 2022-11-28 16:30:13.084346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2c1a6523cd'
down_revision = '4d281f0968fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uniq_name_source', table_name='algorithm_projects_v2')
    op.create_unique_constraint('uniq_name_source_project_id', 'algorithm_projects_v2', ['name', 'source', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_name_source_project_id', 'algorithm_projects_v2', type_='unique')
    op.create_index('uniq_name_source', 'algorithm_projects_v2', ['name', 'source'], unique=True)
    # ### end Alembic commands ###
