"""Removes workflow template is_left

Revision ID: c01cdd2253e4
Revises: 0166249ad82d
Create Date: 2022-09-22 18:15:23.957189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c01cdd2253e4'
down_revision = '0166249ad82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'is_left')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_v2', sa.Column('is_left', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='is_left'))
    # ### end Alembic commands ###
