"""add_mmgr_group_participant_info_and_auth_status

Revision ID: c2a9703b8472
Revises: df7a0b85b0c8
Create Date: 2022-10-10 17:05:59.573061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2a9703b8472'
down_revision = 'df7a0b85b0c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('auth_status', sa.Enum('PENDING', 'AUTHORIZED', 'WITHDRAW', name='authstatus', native_enum=False, create_constraint=False, length=32), nullable=True, comment='auth status'))
    op.add_column('model_groups_v2', sa.Column('participants_info', sa.Text(), nullable=True, comment='participants info'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_groups_v2', 'participants_info')
    op.drop_column('model_groups_v2', 'auth_status')
    # ### end Alembic commands ###
