"""[User]: Add Role and State

Revision ID: c36c504c939d
Revises: b3512a6ce912
Create Date: 2021-03-23 11:35:13.943248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36c504c939d'
down_revision = '80b0a98ce379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_v2', sa.Column('email', sa.String(length=255), nullable=True, comment='email of user'))
    op.add_column('users_v2', sa.Column('name', sa.String(length=255), nullable=True, comment='name of user'))
    op.add_column('users_v2', sa.Column('role', sa.Enum('USER', 'ADMIN', name='role'), nullable=True, comment='role of user'))
    op.add_column('users_v2', sa.Column('state', sa.Enum('ACTIVE', 'DELETED', name='state'), nullable=True, comment='state of user'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_v2', 'state')
    op.drop_column('users_v2', 'role')
    op.drop_column('users_v2', 'name')
    op.drop_column('users_v2', 'email')
    # ### end Alembic commands ###
