"""mmgr support auto update

Revision ID: c3e83aed516c
Revises: 993096ed6fb3
Create Date: 2022-11-01 17:11:34.679389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e83aed516c'
down_revision = '993096ed6fb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('auto_update_status', sa.Enum('INITIAL', 'ACTIVE', 'STOPPED', name='groupautoupdatestatus', native_enum=False, length=64, create_constraint=False), nullable=True, comment='auto update status'))
    op.add_column('model_groups_v2', sa.Column('start_data_batch_id', sa.Integer(), nullable=True, comment='start data_batches id for auto update job'))
    op.add_column('model_jobs_v2', sa.Column('auto_update', sa.Boolean(), server_default=sa.text('0'), nullable=True, comment='is auto update'))
    op.add_column('model_jobs_v2', sa.Column('data_batch_id', sa.Integer(), nullable=True, comment='data_batches id for auto update job'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs_v2', 'data_batch_id')
    op.drop_column('model_jobs_v2', 'auto_update')
    op.drop_column('model_groups_v2', 'start_data_batch_id')
    op.drop_column('model_groups_v2', 'auto_update_status')
    # ### end Alembic commands ###
