"""add_algorithm_project_publish_status

Revision ID: cd52ddd1d2ac
Revises: 554fd3c48986
Create Date: 2022-08-25 13:45:34.551929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd52ddd1d2ac'
down_revision = '554fd3c48986'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithm_projects_v2', sa.Column('publish_status_v2', sa.Enum('UNPUBLISHED', 'PUBLISHED', name='publishstatus', native_enum=False, create_constraint=False, length=32), server_default='UNPUBLISHED', nullable=True, comment='publish status'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithm_projects_v2', 'publish_status_v2')
    # ### end Alembic commands ###
