"""remove_podssnapshots

Revision ID: cf4d3ba429e0
Revises: 2d9c3afaa7fe
Create Date: 2021-09-27 14:33:05.699137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf4d3ba429e0'
down_revision = '2d9c3afaa7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_v2', 'pods_snapshot')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_v2', sa.Column('pods_snapshot', mysql.LONGTEXT(), nullable=True, comment='pods snapshot'))
    # ### end Alembic commands ###
