"""add_config_to_model_group

Revision ID: e3166ab65528
Revises: 56c35c0544e7
Create Date: 2022-01-17 11:27:24.951416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3166ab65528'
down_revision = '56c35c0544e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_groups_v2', sa.Column('algorithm_id', sa.Integer(), nullable=True, comment='algorithm id'))
    op.add_column('model_groups_v2', sa.Column('algorithm_project_id', sa.Integer(), nullable=True, comment='algorithm project id'))
    op.add_column('model_groups_v2', sa.Column('algorithm_type', sa.Enum('UNSPECIFIED', 'NN_LOCAL', 'NN_HORIZONTAL', 'NN_VERTICAL', 'TREE_VERTICAL', name='algorithmtype', native_enum=False, create_constraint=False, length=64), default='UNSPECIFIED', nullable=True, comment='algorithm type'))
    op.add_column('model_groups_v2', sa.Column('authorized', sa.Boolean(), nullable=True, comment='authorized to participants in project'))
    op.add_column('model_groups_v2', sa.Column('config', sa.Text(length=16777215), nullable=True, comment='config'))
    op.add_column('model_groups_v2', sa.Column('intersection_dataset_id', sa.Integer(), nullable=True, comment='intersection dataset id'))
    op.add_column('model_groups_v2', sa.Column('role', sa.Enum('PARTICIPANT', 'COORDINATOR', name='modeljobrole', native_enum=False, create_constraint=False, length=64), default='PARTICIPANT', nullable=True, comment='role'))
    op.add_column('model_groups_v2', sa.Column('uuid', sa.String(length=64), nullable=True, comment='uuid'))
    op.add_column('model_jobs_v2', sa.Column('role', sa.Enum('PARTICIPANT', 'COORDINATOR', name='modeljobrole', native_enum=False, create_constraint=False, length=64), default='PARTICIPANT', nullable=True, comment='role'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_jobs_v2', 'role')
    op.drop_column('model_groups_v2', 'uuid')
    op.drop_column('model_groups_v2', 'role')
    op.drop_column('model_groups_v2', 'intersection_dataset_id')
    op.drop_column('model_groups_v2', 'config')
    op.drop_column('model_groups_v2', 'authorized')
    op.drop_column('model_groups_v2', 'algorithm_type')
    op.drop_column('model_groups_v2', 'algorithm_project_id')
    op.drop_column('model_groups_v2', 'algorithm_id')
    # ### end Alembic commands ###
