"""add_algorithms_table

Revision ID: e9ce77d87969
Revises: 2ffa86e5e692
Create Date: 2021-11-01 11:35:27.910796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ce77d87969'
down_revision = '2ffa86e5e692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithms_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='name'),
    sa.Column('project_id', sa.Integer(), nullable=True, comment='project id'),
    sa.Column('version', sa.Integer(), nullable=True, comment='version'),
    sa.Column('algorithm_type', sa.Enum('UNSPECIFIED', 'NN_LOCAL', 'NN_HORIZONTAL', 'NN_VERTICAL', 'TREE_VERTICAL', name='algorithmtype', native_enum=False, create_constraint=False, length=64), default='UNSPECIFIED', nullable=True, comment='algorithm type'),
    sa.Column('source', sa.Enum('UNSPECIFIED', 'PRESET', 'USER', 'THIRD_PARTY', name='source', native_enum=False, create_constraint=False, length=32), default='UNSPECIFIED', nullable=True, comment='source'),
    sa.Column('creator_id', sa.Integer(), nullable=True, comment='creator user id'),
    sa.Column('fspath', sa.String(length=512), nullable=True, comment='algorithm path'),
    sa.Column('parameter', sa.Text(), nullable=True, comment='parameter'),
    sa.Column('favorite', sa.Boolean(), nullable=True, comment='favorite'),
    sa.Column('cmt', sa.String(length=255), nullable=True, comment='comment'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True, comment='created time'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='updated time'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='deleted time'),
    sa.PrimaryKeyConstraint('id'),
    comment='algorithms',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_name', 'algorithms_v2', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_name', table_name='algorithms_v2')
    op.drop_table('algorithms_v2')
    # ### end Alembic commands ###
