"""add participant table and relationship table

Revision ID: efc25abe02fa
Revises: a1f5564f7d00
Create Date: 2021-09-01 11:53:49.220421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc25abe02fa'
down_revision = 'a1f5564f7d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='participant id'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='participant name'),
    sa.Column('domain_name', sa.String(length=255), nullable=False, comment='participant domain_name'),
    sa.Column('host', sa.String(length=255), nullable=True, comment='participant host'),
    sa.Column('port', sa.Integer(), nullable=True, comment='host port'),
    sa.Column('cmt', sa.Text(), nullable=True, comment='comment'),
    sa.Column('certificates', sa.LargeBinary(), nullable=True, comment='certificates'),
    sa.Column('extra', sa.Text(), nullable=True, comment='extra_info'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created at'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='updated at'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_name'),
    sa.UniqueConstraint('domain_name', name='uniq_domain_name'),
    comment='This is webconsole participant table.',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_table('projects_participants_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='relationship id'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='project_id id'),
    sa.Column('participant_id', sa.Integer(), nullable=False, comment='participants_id id'),
    sa.PrimaryKeyConstraint('id'),
    comment='This is webcocsole projects and participants relationship table.',
    mysql_charset='utf8mb4',
    mysql_engine='innodb'
    )
    op.create_index('idx_participant_id', 'projects_participants_v2', ['participant_id'], unique=False)
    op.create_index('idx_project_id', 'projects_participants_v2', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_project_id', table_name='projects_participants_v2')
    op.drop_index('idx_participant_id', table_name='projects_participants_v2')
    op.drop_table('projects_participants_v2')
    op.drop_table('participants_v2')
    # ### end Alembic commands ###
