"""add_creator_and_create_time

Revision ID: f252b315e730
Revises: 14e747dbcc2f
Create Date: 2022-04-27 17:17:01.269616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f252b315e730'
down_revision = '14e747dbcc2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_groups_v2', 'intersection_dataset_id')
    op.drop_column('model_jobs_v2', 'intersection_dataset_id')
    op.add_column('template_v2', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='created_at'))
    op.add_column('template_v2', sa.Column('creator_username', sa.String(length=255), nullable=True, comment='the username of the creator'))
    op.add_column('template_v2', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='update_at'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template_v2', 'updated_at')
    op.drop_column('template_v2', 'creator_username')
    op.drop_column('template_v2', 'created_at')
    op.add_column('model_jobs_v2', sa.Column('intersection_dataset_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='intersection dataset id'))
    op.add_column('model_groups_v2', sa.Column('intersection_dataset_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='intersection dataset id'))
    # ### end Alembic commands ###
