"""empty message

Revision ID: fefa06dd93cc
Revises: 1b5c86643811
Create Date: 2021-04-02 15:46:24.078703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fefa06dd93cc'
down_revision = '1b5c86643811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_v2', 'config', existing_type=sa.LargeBinary(), type_=sa.LargeBinary(16777215),
                    comment='config')
    op.alter_column('job_v2', 'flapp_snapshot', existing_type=sa.Text(), type_=sa.Text(16777215),
                    comment='flapp_snapshot')
    op.alter_column('job_v2', 'pods_snapshot', existing_type=sa.Text(),
                    type_=sa.Text(16777215), comment='pods_snapshot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_v2', 'config', existing_type=sa.LargeBinary(16777215), type_=mysql.TEXT,
                    comment='config')
    op.alter_column('job_v2', 'flapp_snapshot', existing_type=sa.Text(16777215), type_=mysql.TEXT,
                    comment='flapp_snapshot')
    op.alter_column('job_v2', 'pods_snapshot', existing_type=sa.Text(16777215),
                    type_=mysql.TEXT, comment='pods_snapshot')
    # ### end Alembic commands ###
