"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import fedlearner_webconsole.proto.algorithm_pb2
import fedlearner_webconsole.proto.dataset_pb2
import fedlearner_webconsole.proto.filtering_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class ListAlgorithmProjectsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FILTER_EXP_FIELD_NUMBER: builtins.int

    @property
    def filter_exp(self) -> fedlearner_webconsole.proto.filtering_pb2.FilterExpression: ...

    def __init__(self,
        *,
        filter_exp : typing.Optional[fedlearner_webconsole.proto.filtering_pb2.FilterExpression] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"filter_exp",b"filter_exp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"filter_exp",b"filter_exp"]) -> None: ...
global___ListAlgorithmProjectsRequest = ListAlgorithmProjectsRequest

class ListAlgorithmProjectsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHM_PROJECTS_FIELD_NUMBER: builtins.int

    @property
    def algorithm_projects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[fedlearner_webconsole.proto.algorithm_pb2.AlgorithmProjectPb]: ...

    def __init__(self,
        *,
        algorithm_projects : typing.Optional[typing.Iterable[fedlearner_webconsole.proto.algorithm_pb2.AlgorithmProjectPb]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm_projects",b"algorithm_projects"]) -> None: ...
global___ListAlgorithmProjectsResponse = ListAlgorithmProjectsResponse

class ListAlgorithmsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHM_PROJECT_UUID_FIELD_NUMBER: builtins.int
    algorithm_project_uuid: typing.Text = ...

    def __init__(self,
        *,
        algorithm_project_uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm_project_uuid",b"algorithm_project_uuid"]) -> None: ...
global___ListAlgorithmsRequest = ListAlgorithmsRequest

class ListAlgorithmsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHMS_FIELD_NUMBER: builtins.int

    @property
    def algorithms(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[fedlearner_webconsole.proto.algorithm_pb2.AlgorithmPb]: ...

    def __init__(self,
        *,
        algorithms : typing.Optional[typing.Iterable[fedlearner_webconsole.proto.algorithm_pb2.AlgorithmPb]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithms",b"algorithms"]) -> None: ...
global___ListAlgorithmsResponse = ListAlgorithmsResponse

class GetAlgorithmProjectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHM_PROJECT_UUID_FIELD_NUMBER: builtins.int
    algorithm_project_uuid: typing.Text = ...

    def __init__(self,
        *,
        algorithm_project_uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm_project_uuid",b"algorithm_project_uuid"]) -> None: ...
global___GetAlgorithmProjectRequest = GetAlgorithmProjectRequest

class GetAlgorithmRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHM_UUID_FIELD_NUMBER: builtins.int
    algorithm_uuid: typing.Text = ...

    def __init__(self,
        *,
        algorithm_uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm_uuid",b"algorithm_uuid"]) -> None: ...
global___GetAlgorithmRequest = GetAlgorithmRequest

class GetAlgorithmFilesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ALGORITHM_UUID_FIELD_NUMBER: builtins.int
    algorithm_uuid: typing.Text = ...

    def __init__(self,
        *,
        algorithm_uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"algorithm_uuid",b"algorithm_uuid"]) -> None: ...
global___GetAlgorithmFilesRequest = GetAlgorithmFilesRequest

class GetAlgorithmFilesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    HASH_FIELD_NUMBER: builtins.int
    CHUNK_FIELD_NUMBER: builtins.int
    hash: typing.Text = ...
    chunk: builtins.bytes = ...

    def __init__(self,
        *,
        hash : typing.Text = ...,
        chunk : builtins.bytes = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"chunk",b"chunk",u"hash",b"hash"]) -> None: ...
global___GetAlgorithmFilesResponse = GetAlgorithmFilesResponse

class InformDatasetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UUID_FIELD_NUMBER: builtins.int
    AUTH_STATUS_FIELD_NUMBER: builtins.int
    uuid: typing.Text = ...
    auth_status: typing.Text = ...

    def __init__(self,
        *,
        uuid : typing.Text = ...,
        auth_status : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"auth_status",b"auth_status",u"uuid",b"uuid"]) -> None: ...
global___InformDatasetRequest = InformDatasetRequest

class ListDatasetsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UUID_FIELD_NUMBER: builtins.int
    KIND_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    TIME_RANGE_FIELD_NUMBER: builtins.int
    uuid: typing.Text = ...
    kind: typing.Text = ...
    state: typing.Text = ...

    @property
    def time_range(self) -> fedlearner_webconsole.proto.dataset_pb2.TimeRange: ...

    def __init__(self,
        *,
        uuid : typing.Text = ...,
        kind : typing.Text = ...,
        state : typing.Text = ...,
        time_range : typing.Optional[fedlearner_webconsole.proto.dataset_pb2.TimeRange] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"time_range",b"time_range"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"kind",b"kind",u"state",b"state",u"time_range",b"time_range",u"uuid",b"uuid"]) -> None: ...
global___ListDatasetsRequest = ListDatasetsRequest

class ListDatasetsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    PARTICIPANT_DATASETS_FIELD_NUMBER: builtins.int

    @property
    def participant_datasets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[fedlearner_webconsole.proto.dataset_pb2.ParticipantDatasetRef]: ...

    def __init__(self,
        *,
        participant_datasets : typing.Optional[typing.Iterable[fedlearner_webconsole.proto.dataset_pb2.ParticipantDatasetRef]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"participant_datasets",b"participant_datasets"]) -> None: ...
global___ListDatasetsResponse = ListDatasetsResponse
