"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import fedlearner_webconsole.proto.review_pb2
import google.protobuf.descriptor
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CreateTicketRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TTYPE_FIELD_NUMBER: builtins.int
    CREATOR_USERNAME_FIELD_NUMBER: builtins.int
    DETAILS_FIELD_NUMBER: builtins.int
    ttype: fedlearner_webconsole.proto.review_pb2.TicketType.V = ...
    creator_username: typing.Text = ...

    @property
    def details(self) -> fedlearner_webconsole.proto.review_pb2.TicketDetails: ...

    def __init__(self,
        *,
        ttype : fedlearner_webconsole.proto.review_pb2.TicketType.V = ...,
        creator_username : typing.Text = ...,
        details : typing.Optional[fedlearner_webconsole.proto.review_pb2.TicketDetails] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"details",b"details"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"creator_username",b"creator_username",u"details",b"details",u"ttype",b"ttype"]) -> None: ...
global___CreateTicketRequest = CreateTicketRequest

class GetTicketRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UUID_FIELD_NUMBER: builtins.int
    uuid: typing.Text = ...

    def __init__(self,
        *,
        uuid : typing.Text = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"uuid",b"uuid"]) -> None: ...
global___GetTicketRequest = GetTicketRequest
