"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import fedlearner_webconsole.proto.common_pb2
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.struct_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class CheckHealthRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___CheckHealthRequest = CheckHealthRequest

class CheckHealthResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    APPLICATION_VERSION_FIELD_NUMBER: builtins.int
    HEALTHY_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    healthy: builtins.bool = ...
    message: typing.Text = ...

    @property
    def application_version(self) -> fedlearner_webconsole.proto.common_pb2.ApplicationVersion: ...

    def __init__(self,
        *,
        application_version : typing.Optional[fedlearner_webconsole.proto.common_pb2.ApplicationVersion] = ...,
        healthy : builtins.bool = ...,
        message : typing.Text = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"application_version",b"application_version"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"application_version",b"application_version",u"healthy",b"healthy",u"message",b"message"]) -> None: ...
global___CheckHealthResponse = CheckHealthResponse

class ListFlagsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___ListFlagsRequest = ListFlagsRequest

class ListFlagsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FLAGS_FIELD_NUMBER: builtins.int

    @property
    def flags(self) -> google.protobuf.struct_pb2.Struct: ...

    def __init__(self,
        *,
        flags : typing.Optional[google.protobuf.struct_pb2.Struct] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal[u"flags",b"flags"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"flags",b"flags"]) -> None: ...
global___ListFlagsResponse = ListFlagsResponse

class CheckTeeEnabledRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...

    def __init__(self,
        ) -> None: ...
global___CheckTeeEnabledRequest = CheckTeeEnabledRequest

class CheckTeeEnabledResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TEE_ENABLED_FIELD_NUMBER: builtins.int
    tee_enabled: builtins.bool = ...

    def __init__(self,
        *,
        tee_enabled : builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal[u"tee_enabled",b"tee_enabled"]) -> None: ...
global___CheckTeeEnabledResponse = CheckTeeEnabledResponse
