kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fedlearner-apiserver
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
