apiVersion: v1
kind: Service
metadata:
  name: fedlearner-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fedlearner-apiserver
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
---
