/**
 * @file Python python
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-fill-down',
  false,
  (props: ISvgIconProps) => (
    <svg width="8" height="5" viewBox="0 0 8 5" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M4.30622 4.24922C4.14638 4.4393 3.85377 4.4393 3.69393 4.24922L0.85292 0.870721C0.634116 0.610521 0.819096 0.213281 1.15907 0.213281L6.84108 0.213281C7.18105 0.213281 7.36603 0.610521 7.14723 0.870721L4.30622 4.24922Z"
        fill="#86909C"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
