/**
 * @file ArrowUpFill arrow-up-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-up-fill',
  false,
  (props: ISvgIconProps) => (
    <svg
      width={props.size || 16}
      height={props.size || 16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <circle cx="7.99998" cy="8.0001" r="6.9" fill="currentColor" />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.26849 4.79241L11.1173 7.6412C11.2656 7.78954 11.2656 8.03006 11.1173 8.1784L10.5801 8.71561C10.4317 8.86396 10.1912 8.86396 10.0429 8.71561L8.66732 7.34017L8.6674 11.1659C8.6674 11.3757 8.49733 11.5458 8.28753 11.5458H7.52781C7.31801 11.5458 7.14794 11.3757 7.14794 11.1659L7.14756 7.52443L5.95692 8.71561C5.80857 8.86396 5.56805 8.86396 5.41971 8.71561L4.8825 8.1784C4.73415 8.03006 4.73415 7.78954 4.8825 7.6412L7.73128 4.79241C7.87963 4.64407 8.12015 4.64407 8.26849 4.79241Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
