/**
 * @file ArrowUp arrow-up
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper('arrow-up', false, (props: ISvgIconProps) => (
  <svg
    t="1554866606089"
    className="icon"
    viewBox="0 0 1024 1024"
    p-id="1361"
    width={props.size}
    height={props.size}
  >
    <defs />
    <path
      d="M512 85.333333q18.005333 0 30.336 12.330667l298.666667 298.666667Q853.333333 408.661333 853.333333 426.666667q0 18.346667-12.16 30.506666T810.666667 469.333333q-18.005333 0-30.336-12.330666L554.666667 230.997333V896q0 17.664-12.501334 30.165333T512 938.666667t-30.165333-12.501334T469.333333 896V230.997333l-225.664 226.005334Q231.338667 469.333333 213.333333 469.333333q-18.346667 0-30.506666-12.16T170.666667 426.666667q0-18.005333 12.330666-30.336l298.666667-298.666667Q493.994667 85.333333 512 85.333333z"
      p-id="1362"
    />
  </svg>
));
