/**
 * @file ArrowLeft arrow-left
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-left',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1554866594237"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="1033"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M426.666667 170.666667q17.664 0 30.165333 12.501333T469.333333 213.333333q0 18.005333-12.672 30.336L230.997333 469.333333H896q17.664 0 30.165333 12.501334T938.666667 512t-12.501334 30.165333T896 554.666667H230.997333l225.664 225.664Q469.333333 792.661333 469.333333 810.666667q0 17.664-12.501333 30.165333T426.666667 853.333333q-18.005333 0-30.336-12.330666l-298.666667-298.666667Q85.333333 529.322667 85.333333 512t12.330667-30.336l298.666667-298.666667Q409.002667 170.666667 426.666667 170.666667z"
        p-id="1034"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
