/**
 * @file ArrowRight arrow-right
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-right',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1554866599650"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="1213"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M597.333333 170.666667q18.005333 0 30.336 12.330666l298.666667 298.666667Q938.666667 493.994667 938.666667 512t-12.330667 30.336l-298.666667 298.666667Q615.338667 853.333333 597.333333 853.333333q-18.346667 0-30.506666-12.16T554.666667 810.666667q0-18.005333 12.330666-30.336L793.002667 554.666667H128q-17.664 0-30.165333-12.501334T85.333333 512t12.501334-30.165333T128 469.333333h665.002667l-226.005334-225.664Q554.666667 231.338667 554.666667 213.333333q0-18.346667 12.16-30.506666T597.333333 170.666667z"
        pId="1214"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
