/**
 * @file ArrowDown arrow-down
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-down',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1554866586866"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="853"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 85.333333q17.664 0 30.165333 12.501334T554.666667 128v665.002667l225.664-226.005334Q792.661333 554.666667 810.666667 554.666667q18.346667 0 30.506666 12.16T853.333333 597.333333q0 18.005333-12.330666 30.336l-298.666667 298.666667Q530.005333 938.666667 512 938.666667t-30.336-12.330667l-298.666667-298.666667Q170.666667 615.338667 170.666667 597.333333q0-18.346667 12.16-30.506666T213.333333 554.666667q18.005333 0 30.336 12.330666L469.333333 793.002667V128q0-17.664 12.501334-30.165333T512 85.333333z"
        pId="854"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
