/**
 * @file ArrowFall arrow-fall
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-fall',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M27 3c.6 0 1 .4 1 1v24h8.1s.1 0 .1.1c.4.2.6.6.7 1v.6c0 .3-.1.5-.3.8L25.4 44c-.3.6-.9 1.1-1.4 1-.6.1-1.1-.4-1.4-1L11.3 30.6c-.2-.2-.2-.5-.3-.8v-.1-.1-.1-.2c.1-.5.3-.9.7-1.1 0 0 .1 0 .1-.1h8.1v-24c0-.6.4-1 1-1H27z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
