/**
 * @file ArrowRise arrow-rise
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper('arrow-rise', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 48 48">
    <path fill="none" d="M0 0h48v48H0z" />
    <path d="M20 20h-7.9-.1-.1s-.1 0-.1-.1c-.4-.2-.6-.6-.7-1.1v-.2-.1-.1-.1c0-.3.1-.5.3-.8L22.6 4c.3-.6.9-1.1 1.4-1 .6-.1 1.1.4 1.4 1l11.3 13.4c.2.2.2.5.3.8V18.8c-.1.4-.3.8-.7 1 0 0-.1 0-.1.1h-.1H28v24c0 .6-.4 1-1 1h-6c-.6 0-1-.4-1-1V20z" />
  </svg>
));
