/**
 * @file Python python
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'arrow-fill-right',
  false,
  (props: ISvgIconProps) => (
    <svg width="5" height="8" viewBox="0 0 5 8" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M4.5113 3.69366C4.70138 3.8535 4.70138 4.14611 4.5113 4.30595L1.13281 7.14696C0.872606 7.36576 0.475366 7.18078 0.475366 6.84081V1.1588C0.475366 0.818828 0.872606 0.633847 1.13281 0.852652L4.5113 3.69366Z"
        fill="#86909C"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
