/**
 * @file Bulb bulb
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper('bulb', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 48 48">
    <path d="M30 42c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H18c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h12zM24 1c9.4 0 17 7.8 17 17.4 0 4.2-2.4 8.5-7 13.1-1.3 1.3-2 3.1-2 4.9v.6c0 1.7-1.3 3-3 3H19c-1.7 0-3-1.4-3-3v-.5c0-1.9-.7-3.6-2-4.9-4.6-4.6-7-9-7-13.1C7 8.8 14.6 1 24 1zm0 4c-7.2 0-13 6-13 13.4 0 2.9 1.9 6.4 5.8 10.3 1.9 1.9 3.1 4.5 3.2 7.3h8c.1-2.7 1.3-5.3 3.2-7.3 3.9-3.9 5.8-7.4 5.8-10.3C37 11 31.2 5 24 5z" />
    <path fill="none" d="M0 0h48v48H0z" />
  </svg>
));
