/**
 * @file Calendar calendar
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'calendar',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561631741209"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="235668"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M768 213.12v21.76a21.12 21.12 0 0 1-21.12 21.12H704a21.12 21.12 0 0 1-21.12-21.12v-21.76H341.12v21.76A21.12 21.12 0 0 1 320 256h-42.88A21.12 21.12 0 0 1 256 234.88v-21.76H170.88v213.76h682.24V213.12zM768 128h128a44.16 44.16 0 0 1 42.88 44.8V896a44.16 44.16 0 0 1-42.88 45.44H128a44.16 44.16 0 0 1-42.88-45.44V172.8A44.16 44.16 0 0 1 128 128h128v-21.12a21.76 21.76 0 0 1 21.12-21.76H320a21.76 21.76 0 0 1 21.12 21.76V128h341.76v-21.12a21.76 21.76 0 0 1 21.12-21.76h42.88a21.76 21.76 0 0 1 21.12 21.76zM170.88 512v341.12h682.24V512z"
        pId="235669"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
