/**
 * @file CaretUp caret-up
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'caret-up',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561625757742"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="35575"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M195.2 682.88H832a21.76 21.76 0 0 0 21.12-21.76 20.48 20.48 0 0 0-5.12-13.44l-320-372.48a21.12 21.12 0 0 0-30.08 0L179.2 647.68a21.12 21.12 0 0 0 0 30.08 21.76 21.76 0 0 0 16 5.12z"
        pId="35576"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
