/**
 * @file CaretRight caret-right
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'caret-right',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561625875116"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="41573"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M377.6 179.2l371.2 313.6c6.4 6.4 12.8 19.2 0 32l-371.2 313.6c-6.4 6.4-25.6 6.4-32 0-6.4-6.4-6.4-6.4-6.4-12.8V198.4c0-12.8 6.4-19.2 19.2-19.2 6.4-6.4 12.8-6.4 19.2 0z"
        p-id="41574"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
