/**
 * @file CheckCircleFill check-circle-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'check-circle-fill',
  false,
  (props: ISvgIconProps) => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.00008 1.16675C10.2217 1.16675 12.8334 3.77842 12.8334 7.00008C12.8334 10.2217 10.2217 12.8334 7.00008 12.8334C3.77842 12.8334 1.16675 10.2217 1.16675 7.00008C1.16675 3.77842 3.77842 1.16675 7.00008 1.16675Z"
        fill="#00B42A"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.14096 5.01191L9.47611 5.29313C9.66128 5.44835 9.68542 5.7243 9.53011 5.9094C9.53008 5.90943 9.53006 5.90946 9.52994 5.90941L6.60396 9.39454C6.44853 9.57948 6.17264 9.60358 5.9875 9.44839L5.31721 8.88595L8.52451 5.06575C8.67993 4.88081 8.95583 4.85671 9.14096 5.01191Z"
        fill="white"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M4.19338 7.32429L4.48693 6.99827C4.64605 6.82154 4.91721 6.80429 5.09745 6.95942L7.15529 8.7306L6.59541 9.40428C6.44097 9.59011 6.16513 9.61556 5.97931 9.46112C5.97701 9.45922 5.97474 9.45729 5.97249 9.45534L4.23206 7.94772C4.04942 7.78951 4.02962 7.51321 4.18782 7.33058C4.18965 7.32847 4.19151 7.32637 4.19338 7.32429Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
