/**
 * @file Check check
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'check',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561631650213"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="229010"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M393.6 679.04l467.2-467.84a21.12 21.12 0 0 1 30.08 0l30.08 30.08a21.12 21.12 0 0 1 0 30.08l-512 512a21.12 21.12 0 0 1-30.08 0L106.88 512a21.12 21.12 0 0 1 0-30.08l30.08-30.08a21.12 21.12 0 0 1 30.08 0z"
        pId="229011"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
