/**
 * @file ClockCircle clock-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'clock-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1562244155248"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="16276"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M556.8 467.2H704c12.8 0 19.2 6.4 19.2 19.2v44.8c0 12.8-6.4 19.2-19.2 19.2H492.8c-6.4 0-12.8 0-12.8-6.4s-12.8-6.4-12.8-12.8V320c0-12.8 6.4-19.2 19.2-19.2h44.8c12.8 0 19.2 6.4 19.2 19.2v147.2zM512 896c211.2 0 384-172.8 384-384s-172.8-384-384-384-384 172.8-384 384 172.8 384 384 384z m0 83.2C249.6 979.2 44.8 768 44.8 512S249.6 44.8 512 44.8 979.2 256 979.2 512s-204.8 467.2-467.2 467.2z"
        pId="16277"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
