/**
 * @file CloseCircleFill close-circle-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'close-circle-fill',
  false,
  (props: ISvgIconProps) => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M7.00008 1.16675C10.2218 1.16675 12.8334 3.77842 12.8334 7.00008C12.8334 10.2218 10.2218 12.8334 7.00008 12.8334C3.77842 12.8334 1.16675 10.2218 1.16675 7.00008C1.16675 3.77842 3.77842 1.16675 7.00008 1.16675Z"
        fill="#E63F3F"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M8.89476 4.68747L9.32786 5.12058C9.46455 5.25726 9.46455 5.47887 9.32786 5.61555L7.93563 7.00813L9.32786 8.40029C9.46455 8.53697 9.46455 8.75858 9.32786 8.89526L8.89476 9.32837C8.75808 9.46505 8.53647 9.46505 8.39979 9.32837L7.00696 7.93563L5.61555 9.32786C5.47887 9.46454 5.25726 9.46454 5.12058 9.32786L4.68747 8.89476C4.55079 8.75807 4.55079 8.53647 4.68747 8.39978L6.07829 7.00696L4.68747 5.61606C4.55079 5.47937 4.55079 5.25777 4.68747 5.12108L5.12058 4.68798C5.25726 4.5513 5.47887 4.5513 5.61555 4.68798L7.00696 6.07946L8.39979 4.68747C8.53647 4.55079 8.75808 4.55079 8.89476 4.68747Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
