/**
 * @file CloseCircle close-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'close-circle',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 2c12.2 0 22 9.8 22 22s-9.8 22-22 22S2 36.2 2 24 11.8 2 24 2zm0 4C14.1 6 6 14.1 6 24s8.1 18 18 18 18-8.1 18-18S33.9 6 24 6zm-4.9 10.2l4.9 4.9 5-4.9c.4-.4 1-.4 1.4 0l1.4 1.4c.4.4.4 1 0 1.4l-5 4.9 5 5c.4.4.4 1 0 1.4l-1.4 1.4c-.4.4-1 .4-1.4 0l-5-5-4.9 5c-.4.4-1 .4-1.4 0l-1.4-1.4c-.4-.4-.4-1 0-1.4l4.9-5-4.9-4.9c-.4-.4-.4-1 0-1.4l1.4-1.4c.3-.4 1-.4 1.4 0z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
