/**
 * @file Cloud cloud
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'cloud',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573026156685"
      className="icon"
      viewBox="0 0 1280 1024"
      p-id="31042"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M1087.4 400.2C1079.4 284.2 982.8 192 864 192c-15.2 0-30.2 1.6-44.8 4.6C755.4 116.6 656.2 64 544 64c-169.2 0-311 119.4-344.6 279.6C79.8 392.2 0 508.8 0 640c0 176.8 143.2 320 320 320h672c159 0 288-129 288-288 0-123.6-78.4-231.6-192.6-271.8zM992 864H320c-123.8 0-224-100.2-224-224 0-112.8 83.4-206.2 192-221.8V416c0-141.4 114.6-256 256-256 107 0 198.6 65.6 236.8 158.8 22.4-19.2 51.4-30.8 83.2-30.8 70.6 0 128 57.4 128 128 0 23.6-6.4 45.8-17.6 64.8 5.8-0.6 11.8-0.8 17.6-0.8 106 0 192 86 192 192s-86 192-192 192z"
        p-id="31043"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
