/**
 * @file CloudDownload cloud-download
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'cloud-download',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0-1h48v48H0z" />
      <path d="M36.5 26h2c.5 0 .9.4 1 .9v10.4l2.9-2.9c.4-.4.9-.4 1.3-.1l.1.1 1.4 1.4c.4.4.4.9.1 1.3l-.1.1-7.1 7.1c-.4.4-.9.4-1.3.1l-.1-.1-7.1-7.1c-.4-.4-.4-.9-.1-1.3l.1-.1 1.4-1.4c.4-.4.9-.4 1.3-.1l.1.1 3 3V27c0-.5.4-.9.9-1h2.2-2zM28 6c9.6 0 17.5 7.5 18 17h-4c-.5-7.3-6.6-13-14-13-6.1 0-11.4 3.9-13.3 9.6l-.7 2.1-2.1.6C8.5 23.2 6 26.4 6 30c0 4.4 3.6 8 8 8h10.8l3.8 4H14C7.4 42 2 36.6 2 30c0-5.6 3.8-10.2 8.9-11.6C13.2 11.2 20 6 28 6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
