/**
 * @file Command command
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'command',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M36 4c4.4 0 8 3.6 8 8 0 4.3-3.4 7.9-7.8 8H32v8h4c4.4 0 8 3.6 8 8s-3.6 8-8 8-8-3.6-8-8v-4h-8v4c0 4.4-3.6 8-8 8s-8-3.6-8-8c0-4.3 3.4-7.9 7.8-8H16v-8h-4c-4.4 0-8-3.6-8-8s3.6-8 8-8 8 3.6 8 8v4h8v-4c0-4.4 3.6-8 8-8zM16 32h-4c-2.2 0-4 1.8-4 4s1.8 4 4 4c2.1 0 3.9-1.7 4-3.8V32zm20 0h-4v4c0 2.2 1.8 4 4 4s4-1.8 4-4-1.8-4-4-4zm-8-12h-8v8h8v-8zM12 8c-2.2 0-4 1.8-4 4s1.8 4 4 4h4v-4c0-2.2-1.8-4-4-4zm24 0c-2.1 0-3.9 1.7-4 3.8V16h4c2.2 0 4-1.8 4-4s-1.8-4-4-4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
