/**
 * @file Compass compass
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'compass',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 42c9.9 0 18-8.1 18-18S33.9 6 24 6 6 14.1 6 24s8.1 18 18 18zm0 4C11.8 46 2 36.2 2 24S11.8 2 24 2s22 9.8 22 22-9.8 22-22 22zm4-18l-11.7 5c-.5.2-1.1 0-1.3-.5-.1-.3-.1-.5 0-.8l5.1-11.6L31.7 15c.5-.2 1.1 0 1.3.5.1.3.1.5 0 .8L28 28z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
