/**
 * @file Delete delete
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'delete',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561631961509"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="249074"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M341.12 170.88V128A42.88 42.88 0 0 1 384 85.12h256a42.88 42.88 0 0 1 42.88 42.88v42.88h228.48a32.64 32.64 0 0 1 16.64 0 19.2 19.2 0 0 1 7.68 8.32 28.16 28.16 0 0 1 3.2 16v30.72a29.44 29.44 0 0 1-3.2 16.64 23.68 23.68 0 0 1-7.68 13.44 42.24 42.24 0 0 1-16.64 0h-58.24v640a42.88 42.88 0 0 1-42.24 42.88H213.12a42.88 42.88 0 0 1-42.24-42.88V256h-58.24a42.24 42.24 0 0 1-16.64 0 23.68 23.68 0 0 1-7.68-8.32 29.44 29.44 0 0 1 0-16.64v-33.28a28.16 28.16 0 0 1 0-16 19.2 19.2 0 0 1 7.68-8.32 32.64 32.64 0 0 1 16.64 0zM256 256v597.12h512V256z m149.12 128H448a21.12 21.12 0 0 1 21.12 21.12V704a21.12 21.12 0 0 1-21.12 21.12h-42.88A21.12 21.12 0 0 1 384 704V405.12A21.12 21.12 0 0 1 405.12 384zM576 384h42.88a21.12 21.12 0 0 1 21.12 21.12V704a21.12 21.12 0 0 1-21.12 21.12H576a21.12 21.12 0 0 1-21.12-21.12V405.12A21.12 21.12 0 0 1 576 384z"
        pId="249075"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
