/**
 * @file Desktop desktop
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'desktop',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573026247065"
      class="icon"
      viewBox="0 0 1219 1024"
      pId="33577"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M1140.97981 0H78.06781C35.05981 0 0 34.377143 0 76.55619v641.950477c0 42.179048 35.108571 76.55619 78.06781 76.55619h486.985142v144.335238H364.007619a42.812952 42.812952 0 0 0-43.154286 42.325334c0 23.259429 19.407238 42.276571 43.154286 42.276571h489.130667c23.747048 0 43.154286-19.017143 43.154285-42.276571a42.812952 42.812952 0 0 0-43.154285-42.276572h-201.874286v-144.384H1141.028571c43.008 0 78.06781-34.377143 78.06781-76.55619V76.55619C1219.047619 34.377143 1183.939048 0 1140.97981 0z m-8.192 84.553143v625.956571H86.308571V84.553143H1132.739048z"
        fill="#000000"
        pId="33578"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
