/**
 * @file DoubleDown double-down
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'double-down',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561638054276"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="426663"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M520.32 822.4l346.88-346.88a21.12 21.12 0 0 1 30.08 0l30.08 30.08a21.12 21.12 0 0 1 0 30.08l-376.96 377.6a42.24 42.24 0 0 1-60.16 0l-377.6-377.6a21.12 21.12 0 0 1 0-30.08l30.72-30.08a21.12 21.12 0 0 1 30.08 0z m0-362.24l346.88-347.52a21.12 21.12 0 0 1 30.08 0l30.08 30.72a21.12 21.12 0 0 1 0 30.08L550.4 550.4a42.24 42.24 0 0 1-60.16 0l-377.6-376.96a21.12 21.12 0 0 1 0-30.08l30.72-30.72a21.12 21.12 0 0 1 30.08 0z"
        pId="426664"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
