/**
 * @file DoubleRight double-right
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'double-right',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561638183496"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="434161"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M826.88 515.84L480 168.96a20.48 20.48 0 0 1 0-30.08L512 108.8a21.12 21.12 0 0 1 30.08 0l376.96 376.96a43.52 43.52 0 0 1 0 60.8l-378.88 376.96a21.12 21.12 0 0 1-30.08 0L480 896a20.48 20.48 0 0 1 0-30.08z m-362.88 0L117.12 168.96a21.12 21.12 0 0 1 0-30.08l30.08-30.08a21.12 21.12 0 0 1 30.08 0l376.96 376.96a43.52 43.52 0 0 1 0 60.8l-376.96 376.96a21.12 21.12 0 0 1-30.08 0L117.12 896a21.12 21.12 0 0 1 0-30.08z"
        p-id="434162"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
