/**
 * @file DoubleLeft double-left
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'double-left',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561638432288"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="441689"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M213.76 515.84l346.88 347.52a21.12 21.12 0 0 1 0 30.08l-30.08 30.08a21.12 21.12 0 0 1-30.08 0L123.52 546.56a43.52 43.52 0 0 1 0-60.8L500.48 108.8a21.12 21.12 0 0 1 30.08 0l30.08 30.08a21.12 21.12 0 0 1 0 30.08z m362.24 0l346.88 347.52a21.12 21.12 0 0 1 0 30.08l-30.08 30.08a21.12 21.12 0 0 1-30.08 0L485.76 546.56a43.52 43.52 0 0 1 0-60.8l377.6-376.96a21.12 21.12 0 0 1 30.08 0l30.08 30.08a21.12 21.12 0 0 1 0 30.08z"
        p-id="441690"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
