/**
 * @file DoubleUp double-up
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'double-up',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561637962791"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="419195"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M520.32 209.92L173.44 556.8a21.12 21.12 0 0 1-30.08 0l-30.72-30.08a21.76 21.76 0 0 1 0-30.72l377.6-376.96a42.24 42.24 0 0 1 60.16 0l376.96 376.96a21.76 21.76 0 0 1 0 30.72L896 556.8a21.12 21.12 0 0 1-30.08 0z m0 362.24l-346.88 346.88a21.12 21.12 0 0 1-30.08 0l-30.72-30.08a21.12 21.12 0 0 1 0-30.08l377.6-376.96a42.24 42.24 0 0 1 60.16 0l376.96 376.96a21.12 21.12 0 0 1 0 30.08l-30.08 30.08a21.12 21.12 0 0 1-30.08 0z"
        pId="419196"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
