/**
 * @file Download download
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'download',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561635383787"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="346165"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M896 789.12V896a42.88 42.88 0 0 1-42.88 42.88H170.88A42.88 42.88 0 0 1 128 896v-106.88a21.12 21.12 0 0 1 21.12-21.12H192a21.12 21.12 0 0 1 21.12 21.12v64h597.76v-64A21.12 21.12 0 0 1 832 768h42.88a21.12 21.12 0 0 1 21.12 21.12z m-341.12-192l128-128a21.76 21.76 0 0 1 30.72 0l30.08 30.08a21.12 21.12 0 0 1 0 30.08l-211.2 211.2a21.12 21.12 0 0 1-15.36 6.4 19.2 19.2 0 0 1-14.72-6.4l-211.2-211.2a21.12 21.12 0 0 1 0-30.08L320 470.4a21.12 21.12 0 0 1 30.08 0L469.12 588.8V128a21.76 21.76 0 0 1 21.76-21.12h42.24a21.76 21.76 0 0 1 21.76 21.12z"
        pId="346166"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
