/**
 * @file Down down
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'down',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561636071618"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="396860"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 613.12l346.88-347.52a21.12 21.12 0 0 1 30.08 0l30.08 30.72a21.12 21.12 0 0 1 0 30.08L542.08 704a42.24 42.24 0 0 1-60.16 0L104.96 326.4a21.12 21.12 0 0 1 0-30.08l30.08-30.72a21.12 21.12 0 0 1 30.08 0z"
        p-id="396861"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
