/**
 * @file DownCircle down-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'down-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561626948676"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="77780"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M511.650988 0a511.650988 511.650988 0 1 0 511.650989 511.650988A511.650988 511.650988 0 0 0 511.650988 0z m0 92.837082a418.813906 418.813906 0 1 1-418.813906 418.813906 418.813906 418.813906 0 0 1 418.813906-418.813906zM684.062713 422.304022a23.034765 23.034765 0 0 0-32.807089 0l-139.604636 139.604635-139.604635-139.604635a23.034765 23.034765 0 0 0-32.807089 0l-32.807089 33.505112a23.034765 23.034765 0 0 0 0 32.80709l191.25835 185.674165a23.732788 23.732788 0 0 0 33.505112 0L716.869802 488.616224a23.034765 23.034765 0 0 0 0-32.80709z"
        p-id="77781"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
