/**
 * @file DragArrow drag-arrow
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'drag-arrow',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M26 37h3.9c.6 0 1 .4 1 1 0 .2-.1.4-.2.6L24.8 46c-.3.4-1 .5-1.4.2-.1 0-.1-.1-.2-.2l-5.9-7.4c-.3-.4-.3-1.1.2-1.4.2-.1.4-.2.6-.2H22V26H11v3.9c0 .6-.4 1-1 1-.2 0-.4-.1-.6-.2L2 24.8c-.4-.3-.5-1-.2-1.4 0-.1.1-.1.2-.2l7.4-5.9c.4-.3 1.1-.3 1.4.2.1.2.2.4.2.6V22h11V11h-3.9c-.6 0-1-.4-1-1 0-.2.1-.4.2-.6L23.2 2c.3-.4 1-.5 1.4-.2.1 0 .1.1.2.2l5.9 7.4c.3.4.3 1.1-.2 1.4-.2.1-.4.2-.6.2H26v11h11v-3.9c0-.6.4-1 1-1 .2 0 .4.1.6.2l7.4 5.9c.4.3.5 1 .2 1.4 0 .1-.1.1-.2.2l-7.4 5.9c-.4.3-1.1.3-1.4-.2-.1-.2-.2-.4-.2-.6V26H26v11z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
