/**
 * @file DriveFile drive-file
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'drive-file',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573024160493"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="7868"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M597.333333 85.333333H256c-46.933333 0-84.906667 38.4-84.906667 85.333334L170.666667 853.333333c0 46.933333 37.973333 85.333333 84.906666 85.333334H768c46.933333 0 85.333333-38.4 85.333333-85.333334V341.333333l-256-256zM256 853.333333V170.666667h298.666667v213.333333h213.333333v469.333333H256z"
        p-id="7869"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
