/**
 * @file Edit edit
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'edit',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 40c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h38zM28.9 3.9l.1.1 6.9 6.9c.8.8.8 2 0 2.8l-.7.7L13.6 36H6c-1.1 0-1.9-.8-2-1.9V26.4l20.8-21L26.2 4c.7-.7 1.9-.8 2.7-.1zm-7.1 10.2l-13.7 14L12 32l13.8-13.8-4-4.1zm5.7-5.9l-3 3 4 4 3-3-4-4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
