/**
 * @file EditNoUnderline edit-no-underline
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'edit-no-underline',
  false,
  (props: ISvgIconProps) => (
    <svg
      width={props.size || 14}
      height={props.size || 14}
      viewBox="0 0 14 14"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.9923 4.14848L9.63547 6.79166L4.62709 11.8H2.54572C2.25802 11.8 2.02233 11.5774 2.0015 11.295L2 11.2543V9.17291L6.9923 4.14848ZM9.69573 2.12796L9.73145 2.16085L11.6055 4.0448C11.8177 4.25808 11.8173 4.60283 11.6045 4.81555L11.4028 5.01699L11.4064 5.0207L10.4071 6.01974L7.76094 3.37384L8.57897 2.54981L8.57381 2.5447L8.95868 2.15984C9.16058 1.95794 9.48132 1.94731 9.69573 2.12796Z"
        fill="currentColor"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
