/**
 * @file Email email
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'email',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 6c1.1 0 2 .9 2 2v32c0 1.1-.9 2-2 2H5c-1.1 0-2-.9-2-2V8c0-1.1.9-2 2-2h38zm-2 4H7v28h34V10zm-4.8 5c.3 0 .5.2.6.4v3.1c0 .3-.1.6-.3.7l-.1.1-11.8 8.3c-.2.1-.4.2-.6.2-.2 0-.4 0-.6-.1l-.1-.1-11.7-8.3c-.3-.2-.4-.5-.4-.8v-3c0-.3.2-.5.5-.5.1 0 .2 0 .3.1l12 8.5 12-8.5c.1 0 .2 0 .2-.1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
