/**
 * @file ExclamationCircleFill exclamation-circle-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'exclamation-circle-fill',
  false,
  (props: ISvgIconProps) => (
    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M10 18.75C14.8325 18.75 18.75 14.8325 18.75 10C18.75 5.16751 14.8325 1.25 10 1.25C5.16751 1.25 1.25 5.16751 1.25 10C1.25 14.8325 5.16751 18.75 10 18.75Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.6295 12.3578C10.898 12.3578 11.1156 12.5754 11.1156 12.8439V14.1078C11.1156 14.3763 10.898 14.5939 10.6295 14.5939H9.36563C9.09716 14.5939 8.87952 14.3763 8.87952 14.1078V12.8439C8.87952 12.5754 9.09716 12.3578 9.36563 12.3578H10.6295ZM10.6295 5.21826C10.898 5.21826 11.1156 5.4359 11.1156 5.70437V10.8184C11.1156 11.0869 10.898 11.3046 10.6295 11.3046H9.36563C9.09716 11.3046 8.87952 11.0869 8.87952 10.8184V5.70437C8.87952 5.4359 9.09716 5.21826 9.36563 5.21826H10.6295Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
