/**
 * @file ExclamationCircle exclamation-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'exclamation-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561635094775"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="331919"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M511.650988 930.464894a418.813906 418.813906 0 1 0-418.813906-418.813906 418.813906 418.813906 0 0 0 418.813906 418.813906z m0 92.837083a511.650988 511.650988 0 1 1 511.650989-511.650989 511.650988 511.650988 0 0 1-511.650989 511.650989zM488.616224 255.476483h46.069529A23.732788 23.732788 0 0 1 558.418541 279.209271v302.244035a23.732788 23.732788 0 0 1-23.732788 23.034765H488.616224a23.732788 23.732788 0 0 1-23.732788-23.034765V279.209271A23.732788 23.732788 0 0 1 488.616224 255.476483zM488.616224 767.825494a23.732788 23.732788 0 0 1-23.732788-23.732788V698.023177A23.732788 23.732788 0 0 1 488.616224 674.290389h46.069529A23.732788 23.732788 0 0 1 558.418541 698.023177v46.069529a23.732788 23.732788 0 0 1-23.732788 23.732788z"
        p-id="331920"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
