/**
 * @file Expand expand
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'expand',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M7 28c.6 0 1 .4 1 1v11h11c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H6c-1.1 0-2-.9-2-2V29c0-.6.4-1 1-1h2zM42 4c1.1 0 2 .9 2 2v13c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V8H29c-.6 0-1-.4-1-1V5c0-.6.4-1 1-1h13z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
