/**
 * @file Export export
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'export',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M31 4c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H8v32h23c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H6c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2h25zm4.8 10.7l7.8 7.8c.8.8.8 2 0 2.8L35.8 33c-.4.4-1 .4-1.4 0L33 31.6c-.4-.4-.4-1 0-1.4l4.2-4.2-18.2-.1c-.5 0-1-.4-1-1V23c0-.5.4-.9.9-1h.1l18.6.1-4.6-4.6c-.4-.4-.4-1 0-1.4l1.4-1.4c.4-.4 1.1-.4 1.4 0z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
