/**
 * @file Eye eye
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'eye',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 37c6.5 0 12.5-4.1 18-13-5.4-8.9-11.4-13-18-13S11.4 15.1 6 24c5.5 8.9 11.5 13 18 13zm0-30c8 0 15 4.9 20.8 14.7l.4.6.4.7c.3.6.3 1.4 0 2l-.4.7C39 35.9 32 41 24 41c-7.9 0-14.8-4.9-20.7-14.7l-.3-.5c-.1-.2-.2-.4-.4-.6l-.1-.2c-.3-.6-.3-1.3 0-1.9l.3-.6c.1-.2.2-.3.2-.4C8.9 12 15.8 7 24 7zm0 9c-4.4 0-8 3.6-8 8s3.6 8 8 8 8-3.6 8-8-3.6-8-8-8zm0 4c2.2 0 4 1.8 4 4s-1.8 4-4 4-4-1.8-4-4 1.8-4 4-4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
