/**
 * @file EyeInvisible eye-invisible
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'eye-invisible',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M6.5 3.7l38.2 38.2c.4.4.4 1 0 1.4l-1.4 1.4c-.4.4-1 .4-1.4 0L3.7 6.5c-.4-.4-.4-1 0-1.4l1.4-1.4c.4-.4 1-.4 1.4 0zM8 15.1l2.6 2.6C9 19.4 7.5 21.5 6 24c5.5 8.9 11.5 13 18 13 1.7 0 3.4-.3 5.1-.9l3 3C29.5 40.4 26.8 41 24 41c-8.5 0-15.8-5.7-22-17 1.9-3.5 3.9-6.5 6-8.9zM24 7c8.6 0 16 5.7 22 17-1.9 3.5-3.9 6.4-6.1 8.9l-2.6-2.6c1.6-1.7 3.2-3.8 4.7-6.3-5.4-8.9-11.4-13-18-13-1.7 0-3.4.3-5.1.8l-3-3C18.4 7.6 21.1 7 24 7zm-8 16.1l8.8 8.8h-.9c-4.4 0-8-3.6-8-8 .1-.2.1-.5.1-.8zm8-7.1c4.4 0 8 3.6 8 8v.9L23.1 16h.9z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
