/**
 * @file FileVideo file-video
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'file-video',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1562230220144"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="16379"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M684.8 128H211.2v768h595.2V256H704c-12.8 0-19.2-6.4-19.2-19.2V128zM172.8 44.8h556.8c12.8 0 19.2 6.4 32 12.8l121.6 121.6c6.4 6.4 12.8 19.2 12.8 32v729.6c0 25.6-19.2 44.8-44.8 44.8H172.8c-25.6-6.4-44.8-25.6-44.8-44.8V83.2c0-19.2 19.2-38.4 44.8-38.4z"
        p-id="16380"
      />
      <path
        d="M428.8 697.6c-6.4 6.4-12.8 6.4-12.8 6.4h-6.4c-6.4 0-12.8-6.4-19.2-12.8V428.8v-6.4-6.4c6.4-6.4 12.8-12.8 19.2-12.8h6.4c6.4 0 6.4 0 12.8 6.4l217.6 121.6c6.4 6.4 19.2 12.8 12.8 25.6 6.4 6.4-6.4 19.2-12.8 19.2l-217.6 121.6z"
        p-id="16381"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
