/**
 * @file FileAudio file-audio
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'file-audio',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1562230232620"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="16716"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M684.8 128H211.2v768h595.2V256H704c-12.8 0-19.2-6.4-19.2-19.2V128zM172.8 44.8h556.8c12.8 0 19.2 6.4 32 12.8l121.6 121.6c6.4 6.4 12.8 19.2 12.8 32v729.6c0 25.6-19.2 44.8-44.8 44.8H172.8c-25.6-6.4-44.8-25.6-44.8-44.8V83.2c0-19.2 19.2-38.4 44.8-38.4z"
        pId="16717"
      />
      <path
        d="M563.2 678.4c0 64-51.2 108.8-115.2 108.8s-115.2-51.2-115.2-108.8S384 569.6 448 569.6c12.8 0 32 0 44.8 6.4l-19.2-243.2v-6.4c0-6.4 6.4-12.8 12.8-6.4l198.4 44.8c6.4 0 12.8 6.4 12.8 12.8l6.4 64V448c0 6.4-6.4 12.8-12.8 12.8l-147.2-32s-6.4 0-6.4 6.4l25.6 243.2z"
        pId="16718"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
