/**
 * @file File file
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'file',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1562230224168"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="16491"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M684.8 128H211.2v768h595.2V256H704c-12.8 0-19.2-6.4-19.2-19.2V128zM172.8 44.8h556.8c12.8 0 19.2 6.4 32 12.8l121.6 121.6c6.4 6.4 12.8 19.2 12.8 32v729.6c0 25.6-19.2 44.8-44.8 44.8H172.8c-25.6-6.4-44.8-25.6-44.8-44.8V83.2c0-19.2 19.2-38.4 44.8-38.4z"
        p-id="16492"
      />
      <path
        d="M339.2 428.8h339.2c19.2 0 25.6 6.4 25.6 19.2v44.8c0 12.8-6.4 19.2-19.2 19.2H339.2c-12.8 0-19.2-6.4-19.2-19.2V448c0-12.8 6.4-19.2 19.2-19.2z m0 211.2h192c12.8 0 19.2 6.4 19.2 19.2v44.8c0 12.8-6.4 19.2-19.2 19.2h-192c-12.8 0-19.2-6.4-19.2-19.2v-44.8c0-12.8 6.4-19.2 19.2-19.2z"
        p-id="16493"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
