/**
 * @file FileAddFill file-add-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'file-add-fill',
  false,
  (props: ISvgIconProps) => (
    <svg
      width={props.size || 16}
      height={props.size || 16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.86089 1.875C10.1708 1.875 10.4681 1.99834 10.6869 2.21781L12.9094 4.4462C13.1275 4.6649 13.25 4.96117 13.25 5.27005V13.5417C13.25 13.8638 12.9888 14.125 12.6667 14.125H3.33333C3.01117 14.125 2.75 13.8638 2.75 13.5417V2.45833C2.75 2.13617 3.01117 1.875 3.33333 1.875H9.86089Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.87433 5.91699C7.59818 5.91699 7.37433 6.14085 7.37433 6.41699V7.794H5.99731C5.72117 7.794 5.49731 8.01786 5.49731 8.294V8.54534C5.49731 8.82149 5.72117 9.04534 5.99732 9.04534H7.37433V10.4224C7.37433 10.6985 7.59818 10.9224 7.87433 10.9224H8.12567C8.40181 10.9224 8.62567 10.6985 8.62567 10.4224V9.04534H10.0027C10.2788 9.04534 10.5027 8.82149 10.5027 8.54534V8.294C10.5027 8.01786 10.2788 7.794 10.0027 7.794H8.62567V6.41699C8.62567 6.14085 8.40181 5.91699 8.12567 5.91699H7.87433Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
