/**
 * @file FileImage file-image
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'file-image',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1562230228091"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="16603"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M684.8 128H211.2v768h595.2V256H704c-12.8 0-19.2-6.4-19.2-19.2V128zM172.8 44.8h556.8c12.8 0 19.2 6.4 32 12.8l121.6 121.6c6.4 6.4 12.8 19.2 12.8 32v729.6c0 25.6-19.2 44.8-44.8 44.8H172.8c-25.6-6.4-44.8-25.6-44.8-44.8V83.2c0-19.2 19.2-38.4 44.8-38.4z"
        p-id="16604"
      />
      <path
        d="M320 364.8h83.2c12.8 0 19.2 6.4 19.2 19.2v83.2c0 12.8-6.4 19.2-19.2 19.2H320c-12.8 0-19.2-6.4-19.2-19.2V384c0-12.8 6.4-19.2 19.2-19.2zM748.8 512v268.8c0 6.4-6.4 12.8-12.8 12.8H454.4c-6.4 0-12.8-6.4-12.8-12.8S448 768 448 768l268.8-268.8c6.4-6.4 19.2-6.4 25.6 0 0 0 6.4 6.4 6.4 12.8z"
        p-id="16605"
      />
      <path
        d="M448 608l185.6 185.6H275.2c-6.4 0-12.8-6.4-12.8-12.8s0-6.4 6.4-6.4l160-160c0-12.8 12.8-12.8 19.2-6.4z"
        p-id="16606"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
