/**
 * @file FindReplace find-replace
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'find-replace',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M16 38c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h11zm15-22c6.1 0 11 4.9 11 11 0 2.7-1 5.2-2.6 7.1l3.9 4.7c.4.4.3 1.1-.1 1.4l-1.8 1.5c-.4.3-1.1.3-1.4-.1l-4-4.8c-1.5.8-3.2 1.2-5 1.2-6.1 0-11-4.9-11-11s4.9-11 11-11zm0 4c-3.9 0-7 3.1-7 7s3.1 7 7 7 7-3.1 7-7-3.1-7-7-7zm-15 2c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h11zM43 6c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1V7c0-.6.4-1 1-1h38z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
