/**
 * @file FolderAddFill folder-add-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'folder-add-fill',
  false,
  (props: ISvgIconProps) => (
    <svg
      width={props.size || 16}
      height={props.size || 16}
      viewBox="0 0 16 16"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.05792 2.57031C6.24678 2.57031 6.42589 2.66119 6.54679 2.81837L7.25354 3.73698H13.8055C14.143 3.73698 14.4166 3.99815 14.4166 4.32031V12.847C14.4166 13.1692 14.143 13.4304 13.8055 13.4304H2.19436C1.85686 13.4304 1.58325 13.1692 1.58325 12.847V3.25971C1.58325 2.87896 1.86816 2.57031 2.21962 2.57031H6.05792Z"
        fill="currentColor"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.87433 5.91699C7.59818 5.91699 7.37433 6.14085 7.37433 6.41699V7.794H5.99731C5.72117 7.794 5.49731 8.01786 5.49731 8.294V8.54534C5.49731 8.82149 5.72117 9.04534 5.99732 9.04534H7.37433V10.4224C7.37433 10.6985 7.59818 10.9224 7.87433 10.9224H8.12567C8.40181 10.9224 8.62567 10.6985 8.62567 10.4224V9.04534H10.0027C10.2788 9.04534 10.5027 8.82149 10.5027 8.54534V8.294C10.5027 8.01786 10.2788 7.794 10.0027 7.794H8.62567V6.41699C8.62567 6.14085 8.40181 5.91699 8.12567 5.91699H7.87433Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
