/**
 * @file FolderAdd folder-add
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'folder-add',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M17.3 5c.7 0 1.3.3 1.7.9L21.4 9h22.1c1.4 0 2.4 1 2.4 2.3v29.5c0 1.3-1.1 2.3-2.4 2.3H4.4C3.1 43 2 42 2 40.7V7.4C2 6.1 3 5 4.2 5h13.1zM42 13H6v26h36V13zm-17 5c.6 0 1 .4 1 1v5h5c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-5v5c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-5h-5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h5v-5c0-.6.4-1 1-1h2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
