/**
 * @file Folder folder
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'folder',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M2 8c0-1.1.9-2 2-2h16c1.1 0 2 .9 2 2v2h21.9c1.2 0 2.1.9 2.1 2v28c0 1.1-.9 2-2.1 2H4.1C2.9 42 2 41.1 2 40V8zm40 6H6v24h36V14z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
