/**
 * @file FullscreenExit fullscreen-exit
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'fullscreen-exit',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M32 14V5c0-.6.4-1 1-1h2c.6 0 1 .4 1 1v7h7c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-9c-1.1 0-2-.9-2-2zM16 34v9c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-7H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h9c1.1 0 2 .9 2 2zm18-2h9c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-7v7c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-9c0-1.1.9-2 2-2zM14 16H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h7V5c0-.6.4-1 1-1h2c.6 0 1 .4 1 1v9c0 1.1-.9 2-2 2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
