/**
 * @file History history
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'history',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M26 2c12.2 0 22 9.8 22 22s-9.8 22-22 22c-7.2 0-13.6-3.5-17.6-8.8l3.2-2.4C14.9 39.2 20.1 42 26 42c9.9 0 18-8.1 18-18S35.9 6 26 6C17.1 6 9.7 12.5 8.2 21H10c.2 0 .4.1.6.2.4.3.5.9.3 1.3l-.1.1-4 5.3-.2.2c-.4.3-1 .3-1.3-.1l-.1-.1-4-5.3c-.1-.2-.2-.4-.2-.6 0-.5.4-.9.9-1H4.2C5.7 10.3 14.9 2 26 2zm1 13c.6 0 1 .4 1 1v7h7c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H25c-.6 0-1-.4-1-1V16c0-.6.4-1 1-1h2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
