/**
 * @file Home home
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'home',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561632641104"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="290012"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M448 853.12h106.88v64a21.76 21.76 0 0 0 21.12 21.76H448a21.76 21.76 0 0 0 21.12-21.76v-64z m192 0h213.12v-448L512 179.2 170.88 407.04v448H384v-256a42.88 42.88 0 0 1 42.88-42.24h170.24a42.88 42.88 0 0 1 42.88 42.24v256zM104.32 348.8l384-256a43.52 43.52 0 0 1 47.36 0l384 256a43.52 43.52 0 0 1 19.2 35.84v512a42.88 42.88 0 0 1-42.88 42.88H128a42.88 42.88 0 0 1-42.88-43.52V384a41.6 41.6 0 0 1 19.2-35.2zM469.12 640v213.12h85.76V640z"
        pId="290013"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
