/**
 * @file Idcard idcard
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'idcard',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573031507873"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="49881"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M704 512a64 64 0 1 0 0-128 64 64 0 0 0 0 128z m0 64a128 128 0 1 1 0-256 128 128 0 0 1 0 256z m-192 192a192 192 0 0 1 384 0h-64a128 128 0 1 0-256 0H512zM128 320h320v64H128V320z m0 192h320v64H128V512z m0 192h320v64H128v-64z m0-512a64 64 0 0 0-64 64v576a64 64 0 0 0 64 64h768a64 64 0 0 0 64-64V256a64 64 0 0 0-64-64H128z m0-64h768a128 128 0 0 1 128 128v576a128 128 0 0 1-128 128H128a128 128 0 0 1-128-128V256a128 128 0 0 1 128-128z"
        pId="49882"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
