/**
 * @file Image image
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'image',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561635253006"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="339027"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M755.2 768H284.8a21.12 21.12 0 0 1-21.12-21.12 19.84 19.84 0 0 1 4.48-13.44l145.28-183.68a21.12 21.12 0 0 1 30.08-3.84L534.4 640l204.16-204.16a16.64 16.64 0 0 1 24.32 0A17.28 17.28 0 0 1 768 448v307.2a12.8 12.8 0 0 1-12.8 12.8zM128 938.88a42.88 42.88 0 0 1-42.88-42.88V128A42.88 42.88 0 0 1 128 85.12h768a42.88 42.88 0 0 1 42.88 42.88v768a42.88 42.88 0 0 1-42.88 42.88z m42.88-85.76h682.24V170.88H170.88zM277.12 256h85.76a21.12 21.12 0 0 1 21.12 21.12v85.76a21.12 21.12 0 0 1-21.12 21.12H277.12A21.12 21.12 0 0 1 256 362.88V277.12A21.12 21.12 0 0 1 277.12 256z"
        pId="339028"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
