/**
 * @file Import import
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'import',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M31 4c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H8v32h23c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H6c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2h25zM17.5 22.4l7.8-7.8c.4-.4.9-.4 1.3-.1l.1.1 1.4 1.4c.4.4.4.9.1 1.3l-.1.1-4.6 4.6h18.6c.5 0 .9.4 1 .9v2c0 .5-.4.9-.9 1h-.1l-18.2.1 4.2 4.2c.4.4.4.9.1 1.3l-.1.1-1.4 1.4c-.4.4-.9.4-1.3.1l-.1-.1-7.8-7.8c-.7-.7-.8-1.9-.1-2.7l.1-.1 7.8-7.8-7.8 7.8z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
