/**
 * @file InfoCircleFill info-circle-fill
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'info-circle-fill',
  false,
  (props: ISvgIconProps) => (
    <svg
      viewBox="0 0 12 12"
      width={props.size || 12}
      height={props.size || 12}
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.00008 0.166687C9.22177 0.166687 11.8334 2.77836 11.8334 6.00002C11.8334 9.22171 9.22177 11.8334 6.00008 11.8334C2.77842 11.8334 0.166748 9.22171 0.166748 6.00002C0.166748 2.77836 2.77842 0.166687 6.00008 0.166687Z"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.45214 4.92151C6.55953 4.92151 6.64659 5.00856 6.64659 5.11595L6.64623 7.86148L7.22343 7.8619C7.3437 7.8619 7.4412 7.95941 7.4412 8.07968V8.77654C7.4412 8.89681 7.3437 8.99431 7.22343 8.99431H4.82105C4.70077 8.99431 4.60327 8.89681 4.60327 8.77654V8.07968C4.60327 7.95941 4.70077 7.8619 4.82105 7.8619L5.40179 7.86148V6.06741L5.29023 6.06831C5.16995 6.06831 5.07245 5.9708 5.07245 5.85053V5.14226C5.07245 5.02199 5.16995 4.92449 5.29023 4.92449L5.5831 4.92199C5.58767 4.92167 5.59229 4.92151 5.59694 4.92151H6.45214ZM6.33817 3.01334C6.45845 3.01334 6.55595 3.11084 6.55595 3.23111V4.04C6.55595 4.16028 6.45845 4.25778 6.33817 4.25778H5.52929C5.40901 4.25778 5.31151 4.16028 5.31151 4.04V3.23111C5.31151 3.11084 5.40901 3.01334 5.52929 3.01334H6.33817Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
