/**
 * @file Interaction interaction
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'interaction',
  false,
  (props: ISvgIconProps) => (
    <svg x="0px" y="0px" viewBox="0 0 48 48" xmlSpace="preserve">
      <g>
        <g transform="translate(-672.000000, -193.000000)">
          <g transform="translate(668.000000, 193.000000)">
            <g transform="translate(4.000000, 0.000000)">
              <g>
                <path
                  className="st0"
                  d="M38,16V8H10v8H38z M38,20H26v20h12V20z M22,40V20H10v20H22z M8,4h32c1.1,0,2,0.9,2,2v36
						c0,1.1-0.9,2-2,2H8c-1.1,0-2-0.9-2-2V6C6,4.9,6.9,4,8,4z"
                />
              </g>
            </g>
          </g>
        </g>
      </g>
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
