/**
 * @file Layout layout
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'layout',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1559810663241"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="10807"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M362.666667 170.666667H170.666667v682.666666h192V170.666667z m85.333333 0v682.666666h405.333333V170.666667H448zM132.266667 85.333333h759.466666C917.333333 85.333333 938.666667 106.666667 938.666667 132.266667v759.466666c0 25.6-21.333333 46.933333-46.933334 46.933334H132.266667C106.666667 938.666667 85.333333 917.333333 85.333333 891.733333V132.266667C85.333333 106.666667 106.666667 85.333333 132.266667 85.333333z"
        p-id="10808"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
