/**
 * @file LeftCircle left-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'left-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561627234813"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="90046"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M511.650988 1023.301977a511.650988 511.650988 0 1 1 511.650989-511.650989 511.650988 511.650988 0 0 1-511.650989 511.650989z m0-92.837083a418.813906 418.813906 0 1 0-418.813906-418.813906 418.813906 418.813906 0 0 0 418.813906 418.813906z m86.554874-249.194274l-33.505112 32.80709a23.034765 23.034765 0 0 1-32.807089 0L346.219496 528.403545a23.732788 23.732788 0 0 1 0-33.505113l185.674165-185.674165a23.034765 23.034765 0 0 1 32.807089 0l33.505112 32.80709a23.034765 23.034765 0 0 1 0 32.807089l-139.604635 139.604635 139.604635 139.604635a23.034765 23.034765 0 0 1 0 27.222904z"
        pId="90047"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
