/**
 * @file Link link
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'link',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561630968366"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="183244"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M579.84 242.56a42.56 42.56 0 1 1 60.16 60.16L376.32 566.4a40.96 40.96 0 1 0 57.6 57.6l300.16-299.52a124.48 124.48 0 0 0-176-176L246.4 460.16a202.88 202.88 0 0 0 286.72 286.72l226.56-226.56a42.56 42.56 0 0 1 60.16 60.16l-226.56 226.56a288 288 0 0 1-407.04-407.04l311.68-312.32A209.92 209.92 0 0 1 794.24 384l-299.52 300.16a128 128 0 1 1-178.56-177.92z"
        p-id="183245"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
