/**
 * @file Loading loading
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'loading',
  false,
  (props: ISvgIconProps) => (
    <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M5.99886 0.166748C9.22052 0.166748 11.8322 2.77842 11.8322 6.00008C11.8322 9.22174 9.22052 11.8334 5.99886 11.8334C2.7772 11.8334 0.165527 9.22174 0.165527 6.00008C0.165527 2.77842 2.7772 0.166748 5.99886 0.166748ZM5.99886 2.11119C3.85109 2.11119 2.10997 3.85231 2.10997 6.00008C2.10997 8.14786 3.85109 9.88897 5.99886 9.88897C8.14663 9.88897 9.88775 8.14786 9.88775 6.00008C9.88775 3.85231 8.14663 2.11119 5.99886 2.11119Z"
        fill="url(#paint0_angular)"
      />
      <defs>
        <radialGradient
          id="paint0_angular"
          cx="0"
          cy="0"
          r="1"
          gradientUnits="userSpaceOnUse"
          gradientTransform="translate(5.99886 6.00008) rotate(-23.9625) scale(5.74517 5.76738)"
        >
          <stop offset="0.921737" stop-color="#165DFF" stop-opacity="0" />
          <stop offset="0.944115" stop-color="#165DFF" />
          <stop offset="0.989583" stop-color="#165DFF" />
        </radialGradient>
      </defs>
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
