/**
 * @file Location location
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'location',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462539520"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="12830"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 85.333333C345.6 85.333333 213.333333 217.6 213.333333 384c0 221.866667 298.666667 554.666667 298.666667 554.666667s298.666667-332.8 298.666667-554.666667C810.666667 217.6 678.4 85.333333 512 85.333333zM512 490.666667c-59.733333 0-106.666667-46.933333-106.666667-106.666667s46.933333-106.666667 106.666667-106.666667c59.733333 0 106.666667 46.933333 106.666667 106.666667S571.733333 490.666667 512 490.666667z"
        pId="12831"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
