/**
 * @file Lock lock
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'lock',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 2c6 0 10.8 4.8 11 10.7V16h7c1.1 0 1.9.8 2 1.9V44c0 1-.8 1.9-1.9 2H6c-1.1 0-1.9-.8-2-1.9V18c0-1 .8-1.9 1.9-2H13v-3c0-6.1 4.9-11 11-11zm16 18H8v22h32V20zm-16 5c3.3 0 6 2.7 6 6s-2.7 6-6 6-6-2.7-6-6 2.7-6 6-6zm0 4c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0-23c-3.8 0-6.9 3-7 6.8V16h14v-3c0-3.9-3.1-7-7-7z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
