/**
 * @file Loop loop
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'loop',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462466889"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="11010"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 170.666667 512 42.666667 341.333333 213.333333l170.666667 170.666667L512 256c140.8 0 256 115.2 256 256 0 42.666667-12.8 85.333333-29.866667 119.466667l64 64C832 640 853.333333 580.266667 853.333333 512 853.333333 324.266667 699.733333 170.666667 512 170.666667zM512 768c-140.8 0-256-115.2-256-256 0-42.666667 12.8-85.333333 29.866667-119.466667L221.866667 328.533333C192 384 170.666667 443.733333 170.666667 512c0 187.733333 153.6 341.333333 341.333333 341.333333l0 128 170.666667-170.666667-170.666667-170.666667L512 768z"
        pId="11011"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
