/**
 * @file Man man
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'man',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M41 5c1.1 0 2 .9 2 2v9c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-4.2l-6.4 6.4c2.1 2.7 3.4 6.1 3.4 9.8 0 8.8-7.2 16-16 16S4 36.8 4 28s7.2-16 16-16c3.7 0 7.1 1.3 9.8 3.4L36.2 9H32c-.6 0-1-.4-1-1V6c0-.6.4-1 1-1h9zM20 16c-6.6 0-12 5.4-12 12s5.4 12 12 12 12-5.4 12-12-5.4-12-12-12z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
