/**
 * @file MenuFold menu-fold
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'menu-fold',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 36c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h38zM13.8 17.6c.6 0 1.1.5 1.2 1.1V29c0 .2-.1.4-.2.6-.3.5-1 .7-1.5.5l-.1-.1-8.5-5.1c-.2-.1-.3-.2-.4-.4-.3-.5-.2-1.2.3-1.6l.1-.1 8.5-5.1c.2-.1.4-.1.6-.1zM43 22c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H23c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h20zm0-14c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1V9c0-.6.4-1 1-1h38z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
