/**
 * @file MenuUnfold menu-unfold
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'menu-unfold',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 36c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h38zM6.2 17.7c.2 0 .4.1.6.2l8.5 5.1c.6.3.7 1.1.4 1.6-.1.2-.2.3-.4.4l-8.5 5.1c-.6.3-1.3.2-1.6-.4-.1-.1-.2-.4-.2-.6V18.9c0-.7.5-1.2 1.2-1.2zM43 22c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H23c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h20zm0-14c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1V9c0-.6.4-1 1-1h38z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
