/**
 * @file Message message
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'message',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 3c11.6 0 21 9.4 21 21s-9.4 21-21 21H5.1C3.9 45 3 44.1 3 42.9V24C3 12.4 12.4 3 24 3zm0 4C14.6 7 7 14.6 7 24v17h17c9.4 0 17-7.6 17-17S33.4 7 24 7zm1 21c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H15c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h10zm8-8c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H15c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h18z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
