/**
 * @file MindMapping mind-mapping
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'mind-mapping',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M9 6c1.5 0 2.9.7 3.9 1.8l.1.2c.6.8 1 1.9 1 3 0 2.1-1.2 3.8-3 4.6V23h4c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-4v9.2c0 .6.1 1.1.3 1.5l.1.1.1.1H15c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-3.7c-2.6 0-4.2-2.6-4.3-5.5V15.5c-1.8-.8-3-2.5-3-4.6C4 8.2 6.2 6 9 6zm34 32c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H22c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h21zm0-15c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H22c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h21zm0-14c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H22c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h21z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
