/**
 * @file Minus minus
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'minus',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561629409082"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="138999"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M112.64 469.312h798.72c9.472 0 12.928 1.024 16.384 2.88 3.456 1.856 6.208 4.608 8.064 8.064 1.92 3.456 2.88 6.912 2.88 16.448v30.592c0 9.536-1.024 12.992-2.88 16.448a19.392 19.392 0 0 1-8.064 8.064c-3.456 1.92-6.912 2.88-16.448 2.88H112.704c-9.536 0-12.992-1.024-16.448-2.88a19.392 19.392 0 0 1-8.064-8.064c-1.92-3.456-2.88-6.912-2.88-16.448v-30.592c0-9.536 1.024-12.992 2.88-16.448a19.392 19.392 0 0 1 8.064-8.064c3.456-1.92 6.912-2.88 16.448-2.88z"
        p-id="139000"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
