/**
 * @file Mobile mobile
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'mobile',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M38 2c1.1 0 2 .9 2 2v40c0 1.1-.9 2-2 2H10c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h28zm-2 4H12v36h24V6zM24 33c1.7 0 3 1.3 3 3s-1.3 3-3 3-3-1.3-3-3 1.3-3 3-3zm3-22h.1c.5.1.9.5.9 1v2.1c-.1.5-.5.9-1 .9h-6.1c-.5-.1-.9-.5-.9-1v-2.1c.1-.5.5-.9 1-.9h6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
