/**
 * @file Mosaic mosaic
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'mosaic',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M4 4h8v8H4V4zm0 16h8v8H4v-8zm0 16h8v8H4v-8zm8-24h8v8h-8v-8zm8-8h8v8h-8V4zm0 16h8v8h-8v-8zm0 16h8v8h-8v-8zm8-8h8v8h-8v-8zm0-16h8v8h-8v-8zm8-8h8v8h-8V4zm0 16h8v8h-8v-8zm0 16h8v8h-8v-8zm-24-8h8v8h-8v-8z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
