/**
 * @file Nav nav
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'nav',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1559810659733"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="10682"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M874.666667 661.333333H362.666667v149.333334h512v-149.333334z m0-85.333333v-128H362.666667v128h512zM149.333333 661.333333v149.333334h128v-149.333334H149.333333z m0-85.333333h128v-128H149.333333v128z m213.333334-362.666667v149.333334h512v-149.333334H362.666667z m-85.333334 0H149.333333v149.333334h128v-149.333334zM113.066667 128h795.733333C938.666667 128 960 147.2 960 170.666667v682.666666c0 23.466667-21.333333 42.666667-49.066667 42.666667H113.066667C85.333333 896 64 876.8 64 853.333333V170.666667c0-23.466667 21.333333-42.666667 49.066667-42.666667z"
        p-id="10683"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
