/**
 * @file Notes 笔记
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'notes',
  false,
  (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48">
      <g>
        <g>
          <g transform="translate(8.000000, 4.000000)">
            <path
              d="M2,0 L22,0 L32,10 L32,38 C32,39.1045695 31.1045695,40 30,40 L2,40 C0.8954305,40 -5.31554344e-14,39.1045695 -5.32907052e-14,38 L-5.32907052e-14,2 C-5.34259759e-14,0.8954305 0.8954305,2.02906125e-16 2,0 Z"
              stroke="#333"
              fill="#FFF"
              fillRule="nonzero"
              strokeLinejoin="round"
              strokeWidth="4"
            />
            <path
              d="M8,16 L24,16"
              stroke="#333"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="4"
              fill="none"
              fillRule="evenodd"
            />
            <path
              d="M8,24 L24,24"
              stroke="#333"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="4"
              fill="none"
              fillRule="evenodd"
            />
          </g>
        </g>
      </g>
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
