/**
 * @file Notification notification
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'notification',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561635030564"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="324841"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M426.88 117.76v-32.64A21.12 21.12 0 0 1 448 64h128a21.12 21.12 0 0 1 21.12 21.12v32.64a350.72 350.72 0 0 1 256 341.12V704h64a21.76 21.76 0 0 1 21.76 21.12V768a21.76 21.76 0 0 1-21.76 21.12H106.88a21.76 21.76 0 0 1-21.76-21.12v-42.88a21.76 21.76 0 0 1 21.76-21.12h64V458.88a350.72 350.72 0 0 1 256-341.12zM256 704h512V458.88A261.76 261.76 0 0 0 512 192a261.76 261.76 0 0 0-256 266.88z m149.12 149.12h213.76a21.76 21.76 0 0 1 21.12 21.76v42.24a21.76 21.76 0 0 1-21.12 21.76H405.12a21.76 21.76 0 0 1-21.12-21.76v-42.24a21.76 21.76 0 0 1 21.12-21.76z"
        p-id="324842"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
