/**
 * @file PauseCircle pause-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'pause-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462507508"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="12026"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M384 682.666667l85.333333 0L469.333333 341.333333 384 341.333333 384 682.666667zM512 85.333333C277.333333 85.333333 85.333333 277.333333 85.333333 512s192 426.666667 426.666667 426.666667c234.666667 0 426.666667-192 426.666667-426.666667S746.666667 85.333333 512 85.333333zM512 853.333333c-187.733333 0-341.333333-153.6-341.333333-341.333333s153.6-341.333333 341.333333-341.333333c187.733333 0 341.333333 153.6 341.333333 341.333333S699.733333 853.333333 512 853.333333zM554.666667 682.666667l85.333333 0L640 341.333333l-85.333333 0L554.666667 682.666667z"
        p-id="12027"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
