/**
 * @file PlayCircle play-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'play-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462555449"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="13370"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M426.666667 704l256-192-256-192L426.666667 704zM512 85.333333C277.333333 85.333333 85.333333 277.333333 85.333333 512s192 426.666667 426.666667 426.666667c234.666667 0 426.666667-192 426.666667-426.666667S746.666667 85.333333 512 85.333333zM512 853.333333c-187.733333 0-341.333333-153.6-341.333333-341.333333s153.6-341.333333 341.333333-341.333333c187.733333 0 341.333333 153.6 341.333333 341.333333S699.733333 853.333333 512 853.333333z"
        p-id="13371"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
