/**
 * @file PlayArrow play-arrow
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'play-arrow',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M11.1 4.3l28 18c1.2.8 1.2 2.6 0 3.4l-28 18C9.8 44.5 8 43.6 8 42V6c0-1.6 1.8-2.5 3.1-1.7zm.9 5.4v28.7L34.3 24 12 9.7z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
