/**
 * @file Plus plus
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'plus',
  false,
  (props: ISvgIconProps) => (
    <svg fill="none" viewBox="0 0 12 12" xmlns="http://www.w3.org/2000/svg">
      <path
        clipRule="evenodd"
        d="m5.5 1.99951c-.27614 0-.5.22386-.5.5v2.5h-2.5c-.27614 0-.5.22386-.5.5v1c0 .27614.22386.5.5.5h2.5v2.5c0 .27614.22386.5.5.5h1c.27614 0 .5-.22386.5-.5v-2.5h2.5c.27614 0 .5-.22386.5-.5v-1c0-.27614-.22386-.5-.5-.5h-2.5v-2.5c0-.27614-.22386-.5-.5-.5z"
        fill="currentColor"
        fillRule="evenodd"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
