/**
 * @file Poweroff poweroff
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'poweroff',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M32 7.7c7.1 3.1 12 10.1 12 18.3 0 11-9 20-20 20S4 37 4 26c0-8.2 4.9-15.2 12-18.3v4.5c-4.8 2.8-8 7.9-8 13.9 0 8.8 7.2 16 16 16s16-7.2 16-16c0-5.9-3.2-11.1-8-13.9V7.7zM22 26V4c0-.6.4-1 1-1h2c.6 0 1 .4 1 1v22c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
