/**
 * @file Qrcode qrcode
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'qrcode',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M9 23h14V9H9v14zM7 5h18c1.1 0 2 .9 2 2v18c0 1.1-.9 2-2 2H7c-1.1 0-2-.9-2-2V7c0-1.1.9-2 2-2zm6 8h6v6h-6v-6zM9 34v5h5v-5H9zm-2-4h9c1.1 0 2 .9 2 2v9c0 1.1-.9 2-2 2H7c-1.1 0-2-.9-2-2v-9c0-1.1.9-2 2-2zM34 9v5h5V9h-5zm-2-4h9c1.1 0 2 .9 2 2v9c0 1.1-.9 2-2 2h-9c-1.1 0-2-.9-2-2V7c0-1.1.9-2 2-2zm2 29v5h5v-5h-5zm-2-4h9c1.1 0 2 .9 2 2v9c0 1.1-.9 2-2 2h-9c-1.1 0-2-.9-2-2v-9c0-1.1.9-2 2-2zm-10 0h4v4h-4v-4zm0 7h4v6h-4v-6zm8-15h4v4h-4v-4zm7 0h6v4h-6v-4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
