/**
 * @file Quote quote
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'quote',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M21.8 8.1c.4 0 .6.4.5.8l-.3 2.6c-.1.6-.4.6-.8.6h-.1c-6.7-.6-11.3 4.1-11.9 14.6 1.2-.7 2.6-1.1 4.1-1.1 4.4 0 8 3.6 8 8s-3.6 8-8 8c-4 0-7.3-3-7.9-6.8-.3-.9-.4-3.6-.4-4.9v-.4c0-7 1.7-12.6 4.3-16.2 2.9-3.9 7.2-5.8 12.5-5.2zm21.3 0c.4 0 .6.4.5.8l-.4 2.5c-.1.6-.4.6-.8.6h-.1c-6.7-.6-11.3 4.1-11.9 14.6 1.2-.7 2.6-1.1 4.1-1.1 4.4 0 8 3.6 8 8s-3.6 8-8 8c-4 0-7.3-3-7.9-6.8-.3-.8-.4-3.5-.4-4.8v-.4c0-7 1.7-12.6 4.3-16.2 3-3.9 7.3-5.8 12.6-5.2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
