/**
 * @file Redo redo
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'redo',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M31.9 24.8c-.4.4-.4 1 0 1.4l1.4 1.4c.4.4 1 .4 1.4 0l9.2-9.2c.8-.8.8-2 0-2.8l-9.2-9.2c-.4-.4-1-.4-1.4 0l-1.4 1.4c-.4.4-.4 1 0 1.4l5.8 5.8H18.5c-7.7 0-14 6.3-14 14s6.3 14 14 14h8.7c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1h-8.3c-3.9 0-10-4-10-10s6.1-10 10-10h18.8l-5.8 5.8z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
