/**
 * @file Reply reply
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'reply',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M48 48H0V0h48z" />
      <path d="M23 15.4c12.2 0 22 10 22 22.3 0 .8-.1 1.8-.2 3.1 0 .3-.3.5-.6.4-.1 0-.3-.1-.4-.2l-.3-.5c-.3-.5-.6-.8-.8-1.1-3.6-4.6-9.4-7.2-17.2-7.3H23v9c0 .6-.5 1-1 1-.3 0-.5-.1-.7-.3L4.5 25.2c-.6-.6-.6-1.6 0-2.2L21.2 6.3c.4-.4 1.1-.4 1.5 0 .2.2.3.4.3.7v8.4zm0 4h-4v-5.2L9 24l10 9.9V28h6.1c5.8 0 10.9 1.3 15 3.7-2.5-7.2-9.2-12.3-17.1-12.3z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
