/**
 * @file RightAngle right-angle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'right-angle',
  false,
  (props: ISvgIconProps) => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M7.00008 12.8334C10.2217 12.8334 12.8334 10.2217 12.8334 7.00008C12.8334 3.77842 10.2217 1.16675 7.00008 1.16675C3.77842 1.16675 1.16675 3.77842 1.16675 7.00008C1.16675 10.2217 3.77842 12.8334 7.00008 12.8334Z"
        fill="#FA9600"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.41813 3.81226C7.59711 3.81226 7.74221 3.95735 7.74221 4.13633V7.54571C7.74221 7.72469 7.59711 7.86979 7.41813 7.86979H6.57554C6.39656 7.86979 6.25146 7.72469 6.25146 7.54571V4.13633C6.25146 3.95735 6.39656 3.81226 6.57554 3.81226H7.41813Z"
        fill="white"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.25146 6.70321C6.25146 6.52422 6.39656 6.37913 6.57554 6.37913H9.98492C10.1639 6.37913 10.309 6.52422 10.309 6.70321V7.5458C10.309 7.72478 10.1639 7.86987 9.98492 7.86987H6.57554C6.39656 7.86987 6.25146 7.72478 6.25146 7.5458V6.70321Z"
        fill="white"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
