/**
 * @file RightCircle right-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'right-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561627138171"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="83898"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M511.650988 1023.301977a511.650988 511.650988 0 1 1 511.650989-511.650989 511.650988 511.650988 0 0 1-511.650989 511.650989z m0-92.837083a418.813906 418.813906 0 1 0-418.813906-418.813906 418.813906 418.813906 0 0 0 418.813906 418.813906zM411.833674 691.042945a23.034765 23.034765 0 0 1 0-32.80709l139.604635-139.604635-139.604635-139.604635a23.034765 23.034765 0 0 1 0-32.807089l30.014997-27.222904a23.034765 23.034765 0 0 1 32.807089 0l189.164281 185.674165a23.034765 23.034765 0 0 1 0 32.807089l-186.372188 183.580095a23.034765 23.034765 0 0 1-35.599182 0z"
        p-id="83899"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
