/**
 * @file RobotAdd robot-add
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'robot-add',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M40 29c.6 0 1 .4 1 1v5h5c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1h-5v5c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-5h-5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h5v-5c0-.6.4-1 1-1h2zM27 3c.6 0 1 .4 1 1v4c0 .6-.4 1-1 1h-1v4h13c1.1 0 2 .9 2 2v9h-4v-7H11v22h16v4H9c-1.1 0-2-.9-2-2V15c0-1.1.9-2 2-2h13V9h-1c-.6 0-1-.4-1-1V4c0-.6.4-1 1-1h6zM3 24c.6 0 1 .4 1 1v6c0 .6-.4 1-1 1H1c-.6 0-1-.4-1-1v-6c0-.6.4-1 1-1h2zm18 1v6h-6v-6h6zm12 0v6h-6v-6h6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
