/**
 * @file Robot robot
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'robot',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M27 3c.6 0 1 .4 1 1v4c0 .6-.4 1-1 1h-1v4h13c1.1 0 2 .9 2 2v26c0 1.1-.9 2-2 2H9c-1.1 0-2-.9-2-2V15c0-1.1.9-2 2-2h13V9h-1c-.6 0-1-.4-1-1V4c0-.6.4-1 1-1h6zm10 14H11v22h26V17zM3 24c.6 0 1 .4 1 1v6c0 .6-.4 1-1 1H1c-.6 0-1-.4-1-1v-6c0-.6.4-1 1-1h2zm44 0c.6 0 1 .4 1 1v6c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1v-6c0-.6.4-1 1-1h2zm-26 1v6h-6v-6h6zm12 0v6h-6v-6h6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
