/**
 * @file RotateLeft rotate-left
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'rotate-left',
  false,
  (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 32 32">
      <path d="M5.602 15.933c0-1.381 1.119-2.5 2.5-2.5h10c1.381 0 2.5 1.119 2.5 2.5v10c0 1.381-1.119 2.5-2.5 2.5h-10c-1.381 0-2.5-1.119-2.5-2.5v-10zM8.602 16.433v9h9v-9h-9z" />
      <path d="M9.852 6.567c-0.667 0.385-0.667 1.347 0 1.732l5.25 3.031c0.667 0.385 1.5-0.096 1.5-0.866v-1.531h3.75c1.657 0 3 1.343 3 3v3c0 0.552 0.448 1 1 1h1c0.552 0 1-0.448 1-1v-3c0-3.314-2.686-6-6-6h-3.75v-1.531c0-0.77-0.833-1.251-1.5-0.866l-5.25 3.031z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
