/**
 * @file Save save
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'save',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573026330488"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="34365"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M704 128v128a64 64 0 0 1-64 64H384a64 64 0 0 1-64-64V128H128v768h768V314.496L709.504 128H704zM128 64h581.504a64 64 0 0 1 45.248 18.752l186.496 186.496a64 64 0 0 1 18.752 45.248V896a64 64 0 0 1-64 64H128a64 64 0 0 1-64-64V128a64 64 0 0 1 64-64z m256 64v128h256V128H384z m128 672a192 192 0 1 1 0-384 192 192 0 0 1 0 384z m0-64a128 128 0 1 0 0-256 128 128 0 0 0 0 256z"
        p-id="34366"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
