/**
 * @file Scan scan
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'scan',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M4 15V6c0-1.1.9-2 2-2h9c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H8v7c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1zm4 18v7h7c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H6c-1.1 0-2-.9-2-2v-9c0-.6.4-1 1-1h2c.6 0 1 .4 1 1zm35-17h-2c-.6 0-1-.4-1-1V8h-7c-.6 0-1-.4-1-1V5c0-.6.4-1 1-1h9c1.1 0 2 .9 2 2v9c0 .6-.4 1-1 1zm1 17v9c0 1.1-.9 2-2 2h-9c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h7v-7c0-.6.4-1 1-1h2c.6 0 1 .4 1 1zM5 22h38c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
