/**
 * @file Schedule schedule
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'schedule',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462630870"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="14502"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 85.333333C277.333333 85.333333 85.333333 277.333333 85.333333 512s192 426.666667 426.666667 426.666667c234.666667 0 426.666667-192 426.666667-426.666667S746.666667 85.333333 512 85.333333zM512 853.333333c-187.733333 0-341.333333-153.6-341.333333-341.333333s153.6-341.333333 341.333333-341.333333c187.733333 0 341.333333 153.6 341.333333 341.333333S699.733333 853.333333 512 853.333333z"
        p-id="14503"
      />
      <path
        d="M533.333333 298.666667 469.333333 298.666667 469.333333 554.666667 691.2 691.2 725.333333 635.733333 533.333333 520.533333Z"
        p-id="14504"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
