/**
 * @file Search search
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'search',
  false,
  (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} fill="currentColor" viewBox="0 0 16 16">
      <path d="M12.8 11.22l2.41 2.412a.362.362 0 010 .511l-.607.598a.35.35 0 01-.502 0l-2.368-2.347a6.037 6.037 0 111.067-1.173zM7.82 12.374a4.555 4.555 0 10.021-9.11 4.555 4.555 0 00-.021 9.11z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
