/**
 * @file SelectAll select-all
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'select-all',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M14.6 33.3l-4.9 4.9-2.1-2.1c-.4-.4-1-.4-1.4 0l-1.4 1.4c-.4.4-.4 1 0 1.4L9 43.1c.2.2.3.2.5.3h.2c.2 0 .5-.1.6-.3l7.1-7.1c.4-.4.4-1 0-1.4L16 33.3c-.4-.4-1-.4-1.4 0zM23 37c-.6 0-1 .4-1 1v2c0 .6.4 1 1 1h20c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1H23zm-8.4-17.7l-4.9 4.9-2.1-2.1c-.4-.4-1-.4-1.4 0l-1.4 1.4c-.4.4-.4 1 0 1.4L9 29.1c.2.2.3.2.5.3h.2c.2 0 .5-.1.6-.3l7.1-7.1c.4-.4.4-1 0-1.4L16 19.3c-.4-.4-1-.4-1.4 0zM23 23c-.6 0-1 .4-1 1v2c0 .6.4 1 1 1h20c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1H23zM14.6 5.5l-4.9 4.9-2.2-2.1c-.4-.4-1-.4-1.4 0L4.7 9.7c-.4.4-.4 1 0 1.4l4.2 4.2c.2.2.3.2.5.3h.2c.2 0 .5-.1.6-.3l7.1-7.1c.4-.4.4-1 0-1.4L16 5.5c-.4-.4-1-.4-1.4 0zM23 9c-.6 0-1 .4-1 1v2c0 .6.4 1 1 1h20c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1H23z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
