/**
 * @file SendOne 立即发送
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'send-one',
  false,
  (props: ISvgIconProps) => (
    <svg width={props.size} height={props.size} viewBox="0 0 48 48">
      <g>
        <g>
          <g transform="translate(4.000000, 6.000000)">
            <polygon
              fill="#FFF"
              fillRule="nonzero"
              points="38 -2.84217094e-14 0 14.1382599 20 18.0083363 25.005249 38"
              strokeLinejoin="round"
              strokeWidth="4"
              stroke="#333"
            />
            <path
              d="M22.8391421,19.1799082 L22.8343802,11.1799082"
              strokeLinecap="round"
              transform="translate(22.836761, 15.179908) rotate(45.034105) translate(-22.836761, -15.179908) "
              strokeLinejoin="round"
              strokeWidth="4"
              stroke="#333"
              fill="none"
              fillRule="evenodd"
            />
          </g>
        </g>
      </g>
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
