/**
 * @file Send send
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'send',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M5 17V4c0-1.5 1.5-2.4 2.8-1.8H8l37 20c1.4.7 1.4 2.6.1 3.4l-.1.2-37 20c-1.3.7-2.8-.2-2.9-1.6L5 44V31c0-.5.2-.9.5-1.3l.1-.1 5.6-5.6-5.6-5.6c-.3-.3-.6-.8-.6-1.2V4v13zm31.1 9H14.8L9 31.8v8.8L36.1 26zM9 7.4v8.8l5.8 5.8h21.3L9 7.4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
