/**
 * @file ShareInternal share-internal
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'share-internal',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M9 36c.6 0 1 .4 1 1v3h28v-3c0-.6.4-1 1-1h2c.6 0 1 .4 1 1v5c0 1.1-.9 2-2 2H8c-1.1 0-2-.9-2-2v-5c0-.6.4-1 1-1h2zM32.6 3.3l10 10c.4.4.4.9.1 1.3l-.1.1-9.9 9.9c-.4.4-.9.4-1.3.1l-.1-.1-1.4-1.4c-.4-.4-.4-.9-.1-1.3l.1-.1 5.8-5.8h-.5c-5.7.1-10.3 1.2-14.2 3.3-3.8 2.1-6.8 5.1-8.8 8.9-.3.6-.6 1.3-.9 1.9l-.1.3c-.1.3-.2.6-.4.9-.1.4-.5.7-.9.7H7.8c-.6 0-1-.4-1-1v-.3l.1-.3c.5-1.4 1.1-2.8 1.7-4 2.4-4.6 5.9-8.1 10.4-10.6 4.5-2.4 9.8-3.7 16.6-3.7l-5.8-5.8c-.4-.4-.4-.9-.1-1.3l.1-.1 1.4-1.4c.3-.3.8-.4 1.2-.2h.2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
