/**
 * @file ShareExternal share-external
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'share-external',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M18 18v4h-6v20h24V22h-6v-4h8c1.1 0 2 .9 2 2v24c0 1.1-.9 2-2 2H10c-1.1 0-2-.9-2-2V20c0-1.1.9-2 2-2h8zm7.3-15.6l7.8 7.8c.4.4.4 1 0 1.4L31.6 13c-.4.4-1 .4-1.4 0L26 8.8 25.9 27c0 .5-.4 1-1 1H23c-.5 0-.9-.4-1-.9V27l.1-18.6-4.6 4.6c-.4.4-1 .4-1.4 0l-1.4-1.4c-.4-.4-.4-1 0-1.4l7.8-7.8c.7-.8 2-.8 2.8 0z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
