/**
 * @file Shrink shrink
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'shrink',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M18 28c1.1 0 2 .9 2 2v13c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V32H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h13zM31 4c.6 0 1 .4 1 1v11h11c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H30c-1.1 0-2-.9-2-2V5c0-.6.4-1 1-1h2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
