/**
 * @file SortArrow sort-arrow
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'sort-arrow',
  false,
  (props: ISvgIconProps) => (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        d="M5.78475 9.3417C5.67168 9.20601 5.76817 9 5.9448 9H10.0552C10.2318 9 10.3283 9.20601 10.2152 9.34171L8.38411 11.5391C8.18421 11.7789 7.81579 11.7789 7.61589 11.5391L5.78475 9.3417Z"
        fill="#86909C"
      />
      <path
        d="M5.78475 6.6583C5.67168 6.79399 5.76817 7 5.9448 7H10.0552C10.2318 7 10.3283 6.79399 10.2152 6.65829L8.38411 4.46093C8.18421 4.22106 7.81579 4.22106 7.61589 4.46093L5.78475 6.6583Z"
        fill="#86909C"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
