/**
 * @file SortDescending sort-descending
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'sort-descending',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M12.6 6.4c.2.2.4.5.4.9V43c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V18H4.2c-.3 0-.6-.3-.6-.6 0-.1 0-.2.1-.4L11 6.9l.2-.2c.3-.4.9-.6 1.4-.3zM40 27c.6 0 1 .4 1 1v1.3c0 .3-.1.6-.3.8L29.3 40H40c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H24c-.6 0-1-.4-1-1v-1.8c0-.3.1-.6.3-.8L34.2 31H24c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h16zM33.2 4c.4 0 .8.3.9.6l6.9 18c.2.5-.1 1.1-.6 1.3-.1 0-.2.1-.4.1h-1.9c-.4 0-.8-.3-.9-.7L36.1 20H27l-1.2 3.3c-.1.4-.5.7-.9.7H23c-.6 0-1-.4-1-1 0-.1 0-.2.1-.4l6.9-18c0-.2.3-.4.8-.6h3.4zm-1.6 3.9L28.5 16h6.1l-3-8.1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
