/**
 * @file SortAscending sort-ascending
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'sort-ascending',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M12.6 42.6c.3-.2.4-.5.4-.8V6c0-.6-.4-1-1-1h-2c-.6 0-1 .4-1 1v25H4.2c-.3 0-.6.3-.6.6 0 .1 0 .2.1.4L11 42.1l.2.2c.4.5.9.5 1.4.3zM23.9 21H39c.5 0 .9-.4.9-.8v-2c0-.5-.4-.9-.8-.9H28.9L39.7 8c.2-.3.3-.5.3-.7V5.9c0-.5-.4-.9-.8-.9H23.9c-.5 0-.9.4-.9.8v2c0 .5.4.9.8.9h9.7l-10.2 8.9c-.2.2-.3.4-.3.6V20c0 .5.4.9.8.9l.1.1H39 23.9zm14.4 23h1.9c.1 0 .2 0 .4-.1.5-.2.7-.7.6-1.2v-.1l-6.9-18c-.1-.3-.4-.6-.8-.6H30c-.5.2-.8.3-.9.6v.1l-6.9 18c0 .1-.1.2-.1.4 0 .5.4.9.9 1H24.9c.4 0 .7-.2.9-.5l.1-.1L27 40h9.1l1.2 3.4c.1.4.4.6.8.6h.2zm-3.7-8h-6.1l3-8.1h.1l3 8.1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
