/**
 * @file StarFull star-full
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'star-full',
  false,
  (props: ISvgIconProps) => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M7.2408 10.8C7.08861 10.7268 6.91139 10.7268 6.7592 10.8L3.78203 12.2319C3.39024 12.4204 2.94359 12.1061 2.98868 11.6736L3.32683 8.43064C3.34313 8.27436 3.29248 8.11848 3.18743 8.00162L0.984664 5.55114C0.699033 5.23339 0.864024 4.7256 1.28187 4.63642L4.50431 3.9487C4.65798 3.9159 4.79057 3.81957 4.86925 3.68355L6.5191 0.831355C6.73304 0.461513 7.26696 0.461513 7.4809 0.831355L9.13075 3.68355C9.20942 3.81957 9.34202 3.9159 9.49569 3.9487L12.7181 4.63642C13.136 4.7256 13.301 5.23339 13.0153 5.55114L10.8126 8.00162C10.7075 8.11848 10.6569 8.27436 10.6732 8.43064L11.0113 11.6736C11.0564 12.1061 10.6098 12.4204 10.218 12.2319L7.2408 10.8Z"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
