/**
 * @file Stop stop
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'stop',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 2c12.2 0 22 9.8 22 22s-9.8 22-22 22S2 36.2 2 24 11.8 2 24 2zM6 24c0 9.9 8.1 18 18 18 4.3 0 8.2-1.5 11.3-4L10 12.7c-2.5 3.1-4 7-4 11.3zM24 6c-4.2 0-8.1 1.4-11.2 3.9l25.3 25.3c2.5-3.1 3.9-7 3.9-11.2 0-9.9-8.1-18-18-18z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
