/**
 * @file Storage storage
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'storage',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462694378"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="16028"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M85.333333 810.666667l853.333333 0 0-170.666667L85.333333 640 85.333333 810.666667zM170.666667 682.666667l85.333333 0 0 85.333333L170.666667 768 170.666667 682.666667zM85.333333 213.333333l0 170.666667 853.333333 0L938.666667 213.333333 85.333333 213.333333zM256 341.333333 170.666667 341.333333 170.666667 256l85.333333 0L256 341.333333zM85.333333 597.333333l853.333333 0 0-170.666667L85.333333 426.666667 85.333333 597.333333zM170.666667 469.333333l85.333333 0 0 85.333333L170.666667 554.666667 170.666667 469.333333z"
        p-id="16029"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
