/**
 * @file SubscribeAdd subscribe-add
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'subscribe-add',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24 4v4H10v32l14-8.7 14 8.6V22h4v22c0 1.1-.9 2-2 2-.4 0-.7-.1-1-.3l-14-8.5c-.6-.4-1.4-.4-2.1 0L9 45.7c-.9.6-2.1.3-2.7-.7-.2-.3-.3-.7-.3-1V6c0-1.1.9-2 2-2h16zm12.7-2c.4 0 .6 0 .8.1.2.1.3.2.4.4.1.2.1.3.1.8V8h4.7c.4 0 .6 0 .8.1.2.1.3.2.4.4.1.2.1.3.1.8v1.4c0 .4 0 .6-.1.8-.1.2-.2.3-.4.4-.2.1-.3.1-.8.1H38v4.7c0 .4 0 .6-.1.8-.1.2-.2.3-.4.4-.2.1-.3.1-.8.1h-1.4c-.4 0-.6 0-.8-.1-.2-.1-.3-.2-.4-.4-.1-.2-.1-.3-.1-.8V12h-4.7c-.4 0-.6 0-.8-.1-.2-.1-.3-.2-.4-.4-.1-.2-.1-.3-.1-.8V9.3c0-.4 0-.6.1-.8.1-.2.2-.3.4-.4.2-.1.3-.1.8-.1H34V3.3c0-.4 0-.6.1-.8.1-.2.2-.3.4-.4.2-.1.3-.1.8-.1h1.4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
