/**
 * @file Subscribed subscribed
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'subscribed',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M40 2c1.1 0 2 .9 2 2v40.6c0 1.1-.9 2-2 2-.3 0-.7-.1-1-.2l-14-7.7c-.6-.3-1.3-.3-1.9 0L9 46.4c-1 .5-2.2.2-2.7-.8-.2-.3-.3-.6-.3-1V4c0-1.1.9-2 2-2h32zm-2 4H10v35.3l11.1-6.1c1.8-1 4-1 5.8 0L38 41.3V6zm-6.2 8.3l1.4 1.4c.4.4.4 1 0 1.4L23.3 27c-.4.4-1 .4-1.4 0l-5.7-5.7c-.4-.4-.4-1 0-1.4l1.4-1.4c.4-.4 1-.4 1.4 0l3.5 3.5 7.8-7.8c.5-.3 1.1-.3 1.5.1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
