/**
 * @file Swap swap
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'swap',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M5 14.8v2c0 .5.4.9.9 1h36.6c1.8 0 2.6-2.1 1.5-3.3l-.1-.1-10.3-9.7c-.4-.4-.9-.4-1.3 0l-.1.1-1.4 1.5c-.4.4-.4.9 0 1.3l.1.1 6.6 6.2H6c-.5 0-.9.4-1 .9v2-2zM42 30H5.5c-1.8 0-2.6 2.1-1.5 3.3l.1.1 10.2 9.7c.4.4.9.4 1.3 0l.1-.1 1.4-1.5c.4-.4.4-.9 0-1.3l-.1-.1-6.5-6.1H42c.5 0 .9-.4 1-.9V31c0-.5-.4-.9-.9-1H5.5 42z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
