/**
 * @file Sync sync
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'sync',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1547462711901"
      className="icon"
      viewBox="0 0 1024 1024"
      p-id="16176"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M170.666667 512c0 93.866667 38.4 179.2 102.4 238.933333L170.666667 853.333333l256 0 0-256-93.866667 93.866667C285.866667 648.533333 256 584.533333 256 512c0-110.933333 72.533333-204.8 170.666667-243.2L426.666667 183.466667C281.6 221.866667 170.666667 354.133333 170.666667 512zM853.333333 170.666667l-256 0 0 256 93.866667-93.866667C738.133333 375.466667 768 439.466667 768 512c0 110.933333-72.533333 204.8-170.666667 243.2l0 89.6c145.066667-38.4 256-170.666667 256-328.533333 0-93.866667-38.4-179.2-102.4-238.933333L853.333333 170.666667z"
        p-id="16177"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
