/**
 * @file Thunderbolt thunderbolt
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'thunderbolt',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M27 8.4L12.8 23.8 23 25.7v13.2l13.4-16.2-9.4-1.4V8.4zm4 9.5l9.5 1.5c.4.1.7.2 1 .4.8.7 1 2 .3 2.8L22.5 45.7c-.4.5-.9.7-1.5.7-1.1 0-2-.9-2-2V29L8.5 27c-.4-.1-.7-.2-1-.5-.8-.7-.9-2-.1-2.8L27.5 1.9c.4-.4.9-.6 1.5-.6 1.1 0 2 .9 2 2v14.6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
