/**
 * @file ToBottom to-bottom
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'to-bottom',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 40c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h38zM25 4c.6 0 1 .4 1 1v20h6c.8 0 1.4.6 1.4 1.4 0 .3-.1.7-.3.9l-8 9.4c-.5.6-1.4.7-2 .2l-.2-.2-8-9.4c-.5-.6-.4-1.5.2-2 .3-.2.6-.3.9-.3h6V5c0-.6.4-1 1-1h2z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
