/**
 * @file ToLeft to-left
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'to-left',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 4c.6 0 1 .4 1 1v38c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V5c0-.6.4-1 1-1h2zm-25.6 6.5l1.5 1.5c.4.4.4.9.1 1.3l-.1.1-8.6 8.6H35c.5 0 .9.4 1 .9V25c0 .5-.4.9-.9 1H10.3l8.6 8.6c.4.4.4.9.1 1.3l-.1.1-1.4 1.4c-.4.4-.9.4-1.3.1l-.1-.1L3.3 24.7c-.4-.4-.4-.9-.1-1.3l.1-.1L16 10.6c.3-.3.8-.4 1.2-.2l.2.1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
