/**
 * @file Tool tool
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'tool',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573032519333"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="63423"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path d="M695.68 128a200.32 200.32 0 0 0-191.808 258.56 32 32 0 0 1-8 31.936l-345.152 345.152a77.504 77.504 0 1 0 109.632 109.632l345.152-345.152a32 32 0 0 1 32-8 200.32 200.32 0 0 0 246.848-259.52l-167.04 166.912a32 32 0 0 1-45.184 0L596.48 351.872a32 32 0 0 1 0-45.248l166.912-166.912A200.064 200.064 0 0 0 695.68 128zM431.36 328.32a264.32 264.32 0 0 1 403.2-224.896 32 32 0 0 1 5.76 49.856l-176 176 30.4 30.4 176-176a32 32 0 0 1 49.92 5.76 264.32 264.32 0 0 1-282.752 396.928l-332.288 332.16a141.504 141.504 0 0 1-200.128-200.128l332.16-332.16a265.152 265.152 0 0 1-6.336-57.92z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
