/**
 * @file ToRight to-right
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'to-right',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M43 4c.6 0 1 .4 1 1v38c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V5c0-.6.4-1 1-1h2zM26.4 14.6c.3 0 .7.1.9.3l9.4 8c.6.5.7 1.4.2 2l-.2.2-9.4 8c-.6.5-1.5.4-2-.2-.2-.3-.3-.6-.3-.9v-6H5c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h20v-6c0-.8.6-1.4 1.4-1.4z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
