/**
 * @file ToTop to-top
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'to-top',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M24.9 11.1l.2.2 8 9.4c.5.6.4 1.5-.2 2-.3.2-.6.3-.9.3h-6v20c0 .6-.4 1-1 1h-2c-.6 0-1-.4-1-1V23h-6c-.8 0-1.4-.6-1.4-1.4 0-.3.1-.7.3-.9l8-9.4c.5-.6 1.4-.7 2-.2zM43 4c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H5c-.6 0-1-.4-1-1V5c0-.6.4-1 1-1h38z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
