/**
 * @file Undo undo
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'undo',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M16.1 24.8c.4.4.4 1 0 1.4l-1.4 1.4c-.4.4-1 .4-1.4 0l-9.2-9.2c-.8-.8-.8-2 0-2.8l9.2-9.2c.4-.4 1-.4 1.4 0l1.4 1.4c.4.4.4 1 0 1.4L10.3 15h19.2c7.7 0 14 6.3 14 14s-6.3 14-14 14h-8.7c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h8.3c3.9 0 10-4 10-10s-6.1-10-10-10H10.3l5.8 5.8z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
