/**
 * @file Unlock unlock
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'unlock',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1573032420143"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="62632"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M176 442v454h672V442H176z m0-64h672c35.346 0 64 28.654 64 64v454c0 35.346-28.654 64-64 64H176c-35.346 0-64-28.654-64-64V442c0-35.346 28.654-64 64-64z m336 317c25.405 0 46-20.595 46-46s-20.595-46-46-46-46 20.595-46 46 20.595 46 46 46z m0 64c-60.751 0-110-49.249-110-110s49.249-110 110-110 110 49.249 110 110-49.249 110-110 110z"
        pId="62633"
      />
      <path
        d="M289.526 404.21l-61.819 16.565c-40.31-150.437 48.967-305.068 199.404-345.378C577.55 35.087 732.18 124.364 772.49 274.801l-61.819 16.565c-31.161-116.296-150.699-185.31-266.994-154.15-116.296 31.162-185.311 150.7-154.15 266.995z"
        pId="62634"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
