/**
 * @file UnorderedList unordered-list
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'unordered-list',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M15.9 8h27.3c.4 0 .8.4.8 1v2c0 .6-.4 1-.9 1H15.9c-.5 0-.9-.4-.9-1V9c0-.6.4-1 .9-1zm0 14h27.3c.5 0 .9.4.9 1v2c0 .6-.4 1-.9 1H15.9c-.5 0-.9-.4-.9-1v-2c0-.6.4-1 .9-1zm0 14h27.3c.5 0 .9.4.9 1v2c0 .6-.4 1-.9 1H15.9c-.5 0-.9-.4-.9-1v-2c0-.6.4-1 .9-1zM5.5 21h3c.8 0 1.5.7 1.5 1.5v3c0 .8-.7 1.5-1.5 1.5h-3c-.8 0-1.5-.7-1.5-1.5v-3c0-.8.7-1.5 1.5-1.5zm0-14h3c.8 0 1.5.7 1.5 1.5v3c0 .8-.7 1.5-1.5 1.5h-3c-.8 0-1.5-.7-1.5-1.5v-3C4 7.7 4.7 7 5.5 7zm0 28h3c.8 0 1.5.7 1.5 1.5v3c0 .8-.7 1.5-1.5 1.5h-3c-.8 0-1.5-.7-1.5-1.5v-3c0-.8.7-1.5 1.5-1.5z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
