/**
 * @file UpCircle up-circle
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'up-circle',
  false,
  (props: ISvgIconProps) => (
    <svg
      t="1561626610540"
      class="icon"
      viewBox="0 0 1024 1024"
      pId="59843"
      width={props.size}
      height={props.size}
    >
      <defs />
      <path
        d="M512 981.12A469.12 469.12 0 1 1 981.12 512 469.12 469.12 0 0 1 512 981.12zM512 896a384 384 0 1 0-384-384 384 384 0 0 0 384 384z m158.08-280.96a21.12 21.12 0 0 1-30.08 0l-128-128-128 128a21.12 21.12 0 0 1-30.08 0l-30.08-30.08a21.12 21.12 0 0 1 0-30.08L499.2 384a21.76 21.76 0 0 1 30.72 0l170.24 170.88a21.12 21.12 0 0 1 0 30.08z"
        pId="59844"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
