/**
 * @file UserGroup user-group
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'user-group',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M17 9c-2.8 0-5 2.2-5 5s2.2 5 5 5 5-2.2 5-5-2.2-5-5-5zm-9 5c0-5 4-9 9-9s9 4 9 9-4 9-9 9-9-4-9-9zm3.7 16C8 30 5 33 5 36.8V40h24v-3.2c0-3.8-3-6.8-6.7-6.8H11.7zM1 36.8C1 30.8 5.8 26 11.7 26h10.7C28.2 26 33 30.8 33 36.8v5.4c0 1-.8 1.8-1.8 1.8H2.8c-1 0-1.8-.8-1.8-1.8v-5.4zM45.7 42h-8.9v-4H43v-1.2c0-2-1.7-3.8-4-3.8h-2.6c-.4-1.5-1.1-2.8-2-4H39c4.4 0 8 3.5 8 7.8v3.9c0 .7-.6 1.3-1.3 1.3zM33 20c0-1.1.9-2 2-2s2 .9 2 2-.9 2-2 2-2-.9-2-2zm2-6c-3.3 0-6 2.7-6 6s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
