/**
 * @file UserAdd user-add
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'user-add',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M15 13c0-3.3 2.7-6 6-6s6 2.7 6 6-2.7 6-6 6-6-2.7-6-6zm6-10c-5.5 0-10 4.5-10 10s4.5 10 10 10 10-4.5 10-10S26.5 3 21 3zM8.2 36c.9-3.5 4-6 7.8-6h8c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1h-8C9.4 26 4 31.4 4 38v4c0 1.1.9 2 2 2h18c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1H8v-2c0-.7.1-1.4.2-2zM37 28h-2c-.6 0-1 .4-1 1v5h-5c-.6 0-1 .4-1 1v2c0 .6.4 1 1 1h5v5c0 .6.4 1 1 1h2c.6 0 1-.4 1-1v-5h5c.6 0 1-.4 1-1v-2c0-.6-.4-1-1-1h-5v-5c0-.6-.4-1-1-1z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
