/**
 * @file User user
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'user',
  false,
  (props: ISvgIconProps) => (
    <svg viewBox="0 0 48 48">
      <path fill="none" d="M0 0h48v48H0z" />
      <path d="M30 26c6.6 0 12 5.4 12 12v6c0 1.1-.9 2-2 2H8c-1.1 0-2-.9-2-2v-6c0-6.6 5.4-12 12-12h12zm0 4H18c-4.4 0-8 3.6-8 8v4h28v-4c0-4.4-3.6-8-8-8zM24 3c5.5 0 10 4.5 10 10s-4.5 10-10 10-10-4.5-10-10S18.5 3 24 3zm0 4c-3.3 0-6 2.7-6 6s2.7 6 6 6 6-2.7 6-6-2.7-6-6-6z" />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
