/**
 * @file ZoomOut zoom-out
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper('zoom-out', false, (props: ISvgIconProps) => (
  <svg viewBox="0 0 48 48">
    <path fill="none" d="M0 0h48v48H0z" />
    <path d="M22 2c11 0 20 9 20 20 0 4.8-1.7 9.2-4.5 12.7l7.9 7.9c.4.4.4 1 0 1.4L44 45.4c-.4.4-1 .4-1.4 0l-7.9-7.9C31.2 40.3 26.8 42 22 42 11 42 2 33 2 22S11 2 22 2zm0 4C13.2 6 6 13.2 6 22s7.2 16 16 16 16-7.2 16-16S30.8 6 22 6zm7 14c.6 0 1 .4 1 1v2c0 .6-.4 1-1 1H15c-.6 0-1-.4-1-1v-2c0-.6.4-1 1-1h14z" />
  </svg>
));
