// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pairing_service.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CtrlFlag int32

const (
	CtrlFlag_CREATE   CtrlFlag = 0
	CtrlFlag_SHUTDOWN CtrlFlag = 1
	CtrlFlag_FINISH   CtrlFlag = 2
)

var CtrlFlag_name = map[int32]string{
	0: "CREATE",
	1: "SHUTDOWN",
	2: "FINISH",
}

var CtrlFlag_value = map[string]int32{
	"CREATE":   0,
	"SHUTDOWN": 1,
	"FINISH":   2,
}

func (x CtrlFlag) String() string {
	return proto.EnumName(CtrlFlag_name, int32(x))
}

func (CtrlFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_508234a4704e8446, []int{0}
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_508234a4704e8446, []int{0}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type PairRequest struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	MasterPairs          []*Pair  `protobuf:"bytes,2,rep,name=master_pairs,json=masterPairs,proto3" json:"master_pairs,omitempty"`
	WorkerPairs          []*Pair  `protobuf:"bytes,3,rep,name=worker_pairs,json=workerPairs,proto3" json:"worker_pairs,omitempty"`
	CtrlFlag             CtrlFlag `protobuf:"varint,4,opt,name=ctrl_flag,json=ctrlFlag,proto3,enum=proto.CtrlFlag" json:"ctrl_flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairRequest) Reset()         { *m = PairRequest{} }
func (m *PairRequest) String() string { return proto.CompactTextString(m) }
func (*PairRequest) ProtoMessage()    {}
func (*PairRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_508234a4704e8446, []int{1}
}

func (m *PairRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairRequest.Unmarshal(m, b)
}
func (m *PairRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairRequest.Marshal(b, m, deterministic)
}
func (m *PairRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairRequest.Merge(m, src)
}
func (m *PairRequest) XXX_Size() int {
	return xxx_messageInfo_PairRequest.Size(m)
}
func (m *PairRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PairRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PairRequest proto.InternalMessageInfo

func (m *PairRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *PairRequest) GetMasterPairs() []*Pair {
	if m != nil {
		return m.MasterPairs
	}
	return nil
}

func (m *PairRequest) GetWorkerPairs() []*Pair {
	if m != nil {
		return m.WorkerPairs
	}
	return nil
}

func (m *PairRequest) GetCtrlFlag() CtrlFlag {
	if m != nil {
		return m.CtrlFlag
	}
	return CtrlFlag_CREATE
}

type Pair struct {
	LeaderId             string   `protobuf:"bytes,1,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	FollowerId           string   `protobuf:"bytes,2,opt,name=follower_id,json=followerId,proto3" json:"follower_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_508234a4704e8446, []int{2}
}

func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (m *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(m, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetLeaderId() string {
	if m != nil {
		return m.LeaderId
	}
	return ""
}

func (m *Pair) GetFollowerId() string {
	if m != nil {
		return m.FollowerId
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CtrlFlag", CtrlFlag_name, CtrlFlag_value)
	proto.RegisterType((*Status)(nil), "proto.Status")
	proto.RegisterType((*PairRequest)(nil), "proto.PairRequest")
	proto.RegisterType((*Pair)(nil), "proto.Pair")
}

func init() { proto.RegisterFile("pairing_service.proto", fileDescriptor_508234a4704e8446) }

var fileDescriptor_508234a4704e8446 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0x71, 0x9a, 0x44, 0xc9, 0x38, 0x2d, 0xd1, 0x4a, 0x95, 0x22, 0x38, 0x10, 0x85, 0x4b,
	0x40, 0xc8, 0x46, 0xe1, 0xd8, 0x53, 0x69, 0x1b, 0xc5, 0x07, 0x4a, 0x65, 0x17, 0x21, 0x71, 0xb1,
	0xd6, 0xde, 0x89, 0xb1, 0xba, 0xf1, 0x2e, 0xb3, 0x6b, 0xaa, 0xfe, 0x2d, 0x7e, 0x21, 0xf2, 0xae,
	0x03, 0x1c, 0xb8, 0x78, 0x46, 0x6f, 0x3e, 0x3f, 0xbd, 0xd9, 0x81, 0x73, 0xcd, 0x6b, 0xaa, 0x9b,
	0x2a, 0x37, 0x48, 0x3f, 0xeb, 0x12, 0x23, 0x4d, 0xca, 0x2a, 0x36, 0x72, 0x65, 0x75, 0x09, 0xe3,
	0xcc, 0x72, 0xdb, 0x1a, 0xc6, 0x60, 0x58, 0x2a, 0x81, 0x8b, 0x60, 0x19, 0xac, 0x47, 0xa9, 0xeb,
	0xd9, 0x6b, 0x38, 0x45, 0x22, 0x45, 0xf9, 0x01, 0x8d, 0xe1, 0x15, 0x2e, 0x06, 0xcb, 0x60, 0x3d,
	0x4d, 0x67, 0x4e, 0xfc, 0xe4, 0xb5, 0xd5, 0xaf, 0x00, 0xc2, 0x3b, 0x5e, 0x53, 0x8a, 0x3f, 0x5a,
	0x34, 0x96, 0x9d, 0xc3, 0x98, 0x6b, 0x9d, 0xd7, 0xc2, 0x59, 0x4d, 0xd3, 0x11, 0xd7, 0x3a, 0x11,
	0x2c, 0x82, 0xd9, 0x81, 0x1b, 0x8b, 0x94, 0x77, 0x81, 0xcc, 0x62, 0xb0, 0x3c, 0x59, 0x87, 0x9b,
	0xd0, 0xc7, 0x89, 0x9c, 0x41, 0xe8, 0x81, 0xae, 0x37, 0x1d, 0xff, 0xa8, 0xe8, 0xe1, 0x0f, 0x7f,
	0xf2, 0x1f, 0xde, 0x03, 0x9e, 0x7f, 0x07, 0xd3, 0xd2, 0x92, 0xcc, 0xf7, 0x92, 0x57, 0x8b, 0xe1,
	0x32, 0x58, 0x9f, 0x6d, 0x9e, 0xf7, 0xf0, 0x95, 0x25, 0xb9, 0x95, 0xbc, 0x4a, 0x27, 0x65, 0xdf,
	0xad, 0xae, 0x61, 0xd8, 0xfd, 0xc6, 0x5e, 0xc2, 0x54, 0x22, 0x17, 0x48, 0x7f, 0xf3, 0x4e, 0xbc,
	0x90, 0x08, 0xf6, 0x0a, 0xc2, 0xbd, 0x92, 0x52, 0x3d, 0xfa, 0xb1, 0x5f, 0x1e, 0x8e, 0x52, 0x22,
	0xde, 0xbe, 0x87, 0xc9, 0xd1, 0x9b, 0x01, 0x8c, 0xaf, 0xd2, 0x9b, 0xcb, 0xfb, 0x9b, 0xf9, 0x33,
	0x36, 0x83, 0x49, 0xb6, 0xfb, 0x72, 0x7f, 0xfd, 0xf9, 0xeb, 0xed, 0x3c, 0xe8, 0x26, 0xdb, 0xe4,
	0x36, 0xc9, 0x76, 0xf3, 0xc1, 0xe6, 0x02, 0xce, 0xee, 0xfc, 0x3d, 0x32, 0x7f, 0x0e, 0xf6, 0xa6,
	0x4f, 0xc2, 0xfe, 0xdd, 0xcc, 0x3f, 0xe5, 0x8b, 0xd3, 0x5e, 0xf3, 0x27, 0xfa, 0xb8, 0xfb, 0xb6,
	0xad, 0x6a, 0xfb, 0xbd, 0x2d, 0xa2, 0x52, 0x1d, 0xe2, 0xe2, 0xc9, 0xa2, 0xe0, 0x4d, 0x89, 0xf1,
	0x1e, 0x85, 0x44, 0x4e, 0x0d, 0x52, 0x2c, 0x50, 0x4b, 0xf5, 0x14, 0x3f, 0xb4, 0x05, 0x52, 0x83,
	0x16, 0x4d, 0xae, 0x34, 0x12, 0xb7, 0x8a, 0x62, 0x67, 0x75, 0xe1, 0xbe, 0xc5, 0xd8, 0x95, 0x0f,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf1, 0x4c, 0xc9, 0x1d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PairingServiceClient is the client API for PairingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PairingServiceClient interface {
	Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*Status, error)
}

type pairingServiceClient struct {
	cc *grpc.ClientConn
}

func NewPairingServiceClient(cc *grpc.ClientConn) PairingServiceClient {
	return &pairingServiceClient{cc}
}

func (c *pairingServiceClient) Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/proto.PairingService/Pair", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PairingServiceServer is the server API for PairingService service.
type PairingServiceServer interface {
	Pair(context.Context, *PairRequest) (*Status, error)
}

// UnimplementedPairingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPairingServiceServer struct {
}

func (*UnimplementedPairingServiceServer) Pair(ctx context.Context, req *PairRequest) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pair not implemented")
}

func RegisterPairingServiceServer(s *grpc.Server, srv PairingServiceServer) {
	s.RegisterService(&_PairingService_serviceDesc, srv)
}

func _PairingService_Pair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PairingServiceServer).Pair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PairingService/Pair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PairingServiceServer).Pair(ctx, req.(*PairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PairingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PairingService",
	HandlerType: (*PairingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pair",
			Handler:    _PairingService_Pair_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pairing_service.proto",
}
