apiVersion: v1
appVersion: 6.8.2
description: Flexible and powerful open source, distributed real-time search and analytics
  engine.
home: https://www.elastic.co/products/elasticsearch
icon: https://static-www.elastic.co/assets/blteb1c97719574938d/logo-elastic-elasticsearch-lt.svg
maintainers:
- email: christian@jetstack.io
  name: simonswine
- email: michael.haselton@gmail.com
  name: icereval
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: cedric@desaintmartin.fr
  name: desaintmartin
- email: goonohc@gmail.com
  name: KongZ
- email: hfernandez@mesosphere.com
  name: hectorj2f
name: elasticsearch
sources:
- https://www.elastic.co/products/elasticsearch
- https://github.com/jetstack/elasticsearch-pet
- https://github.com/giantswarm/kubernetes-elastic-stack
- https://github.com/GoogleCloudPlatform/elasticsearch-docker
- https://github.com/clockworksoul/helm-elasticsearch
- https://github.com/pires/kubernetes-elasticsearch-cluster
version: 1.32.0
