/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/bytedance/fedlearner/deploy/kubernetes_operator/pkg/apis/fedlearner.k8s.io/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrainingSets implements TrainingSetInterface
type FakeTrainingSets struct {
	Fake *FakeFedlearnerV1alpha2
	ns   string
}

var trainingsetsResource = schema.GroupVersionResource{Group: "fedlearner.k8s.io", Version: "v1alpha2", Resource: "trainingsets"}

var trainingsetsKind = schema.GroupVersionKind{Group: "fedlearner.k8s.io", Version: "v1alpha2", Kind: "TrainingSet"}

// Get takes name of the trainingSet, and returns the corresponding trainingSet object, and an error if there is any.
func (c *FakeTrainingSets) Get(name string, options v1.GetOptions) (result *v1alpha2.TrainingSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(trainingsetsResource, c.ns, name), &v1alpha2.TrainingSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.TrainingSet), err
}

// List takes label and field selectors, and returns the list of TrainingSets that match those selectors.
func (c *FakeTrainingSets) List(opts v1.ListOptions) (result *v1alpha2.TrainingSetList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(trainingsetsResource, trainingsetsKind, c.ns, opts), &v1alpha2.TrainingSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.TrainingSetList{ListMeta: obj.(*v1alpha2.TrainingSetList).ListMeta}
	for _, item := range obj.(*v1alpha2.TrainingSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trainingSets.
func (c *FakeTrainingSets) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(trainingsetsResource, c.ns, opts))

}

// Create takes the representation of a trainingSet and creates it.  Returns the server's representation of the trainingSet, and an error, if there is any.
func (c *FakeTrainingSets) Create(trainingSet *v1alpha2.TrainingSet) (result *v1alpha2.TrainingSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(trainingsetsResource, c.ns, trainingSet), &v1alpha2.TrainingSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.TrainingSet), err
}

// Update takes the representation of a trainingSet and updates it. Returns the server's representation of the trainingSet, and an error, if there is any.
func (c *FakeTrainingSets) Update(trainingSet *v1alpha2.TrainingSet) (result *v1alpha2.TrainingSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(trainingsetsResource, c.ns, trainingSet), &v1alpha2.TrainingSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.TrainingSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTrainingSets) UpdateStatus(trainingSet *v1alpha2.TrainingSet) (*v1alpha2.TrainingSet, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(trainingsetsResource, "status", c.ns, trainingSet), &v1alpha2.TrainingSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.TrainingSet), err
}

// Delete takes name of the trainingSet and deletes it. Returns an error if one occurs.
func (c *FakeTrainingSets) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(trainingsetsResource, c.ns, name), &v1alpha2.TrainingSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrainingSets) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(trainingsetsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.TrainingSetList{})
	return err
}

// Patch applies the patch and returns the patched trainingSet.
func (c *FakeTrainingSets) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.TrainingSet, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(trainingsetsResource, c.ns, name, pt, data, subresources...), &v1alpha2.TrainingSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.TrainingSet), err
}
