{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fedlearner-proxy-server
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ .Files.Get .Values.tls.server.intermediate | b64enc }}
  tls.crt: {{ .Files.Get .Values.tls.server.cert | b64enc }}
  tls.key: {{ .Files.Get .Values.tls.server.key | b64enc }}
---
{{- $intermediate := .Files.Get .Values.tls.server.intermediate -}}
{{- $ca := .Files.Get .Values.tls.server.ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  ca.crt: {{ printf "%s%s" $intermediate $ca | b64enc }}
---
{{- $intermediate = .Files.Get .Values.tls.client.intermediate -}}
{{- $ca = .Files.Get .Values.tls.client.ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: fedlearner-proxy-client
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  client.pem: {{ .Files.Get .Values.tls.client.cert | b64enc }}
  client.key: {{ .Files.Get .Values.tls.client.key | b64enc }}
  all.pem: {{ printf "%s%s" $intermediate $ca | b64enc }}
{{- end }}
