apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flapp-operator
  name: flapp-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flapp-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flapp-operator
    spec:
      containers:
        - args:
            - --port=8100
            - --namespace={{ .Release.Namespace }}
            - --leader-election=true
            - --leader-election-lock-namespace={{ .Release.Namespace }}
            - --resync-interval=5
          command:
            - /app
          image: "{{ .Values.image.operatorRepository }}:{{ .Values.image.operatorTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: flapp-operator
          ports:
            - containerPort: 8100
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      serviceAccountName: flapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flapp-apiserver
  name: flapp-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: flapp-apiserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flapp-apiserver
    spec:
      containers:
        - args:
            - --port=8101
          command:
            - /app
          image: "{{ .Values.image.apiserverRepository }}:{{ .Values.image.apiserverTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: flapp-apiserver
          ports:
            - containerPort: 8101
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      serviceAccountName: flapp
