apiVersion: v1
kind: Service
metadata:
  name: flapp-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: flapp-operator
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: flapp-apiserver
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: flapp-apiserver
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
---
