apiVersion: v1
appVersion: 1.1.0
description: Elasticsearch stats exporter for Prometheus
home: https://github.com/justwatchcom/elasticsearch_exporter
keywords:
- metrics
- elasticsearch
- monitoring
kubeVersion: '>=1.10.0-0'
maintainers:
- email: sven.mueller@commercetools.com
  name: svenmueller
- email: carlos@carlosbecker.com
  name: caarlos0
name: elasticsearch-exporter
sources:
- https://github.com/justwatchcom/elasticsearch_exporter
version: 2.1.0
