/**
 * @file Default default
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'default',
  false,
  (props: ISvgIconProps) => (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M9.91403 1.7002C10.2328 1.7002 10.5386 1.82706 10.7637 2.0528L13.0496 4.34485C13.274 4.5698 13.4 4.87454 13.4 5.19225V13.7002C13.4 14.0316 13.1313 14.3002 12.8 14.3002H3.19998C2.8686 14.3002 2.59998 14.0316 2.59998 13.7002V2.3002C2.59998 1.96882 2.8686 1.7002 3.19998 1.7002H9.91403ZM8.29998 9.2002C8.46566 9.2002 8.59998 9.33451 8.59998 9.5002V10.2369C8.59998 10.4026 8.46566 10.5369 8.29998 10.5369H5.59998C5.43429 10.5369 5.29998 10.4026 5.29998 10.2369V9.5002C5.29998 9.33451 5.43429 9.2002 5.59998 9.2002H8.29998ZM10.4 6.04139C10.5657 6.04139 10.7 6.17571 10.7 6.34139V7.1002C10.7 7.26588 10.5657 7.4002 10.4 7.4002H5.59998C5.43429 7.4002 5.29998 7.26588 5.29998 7.1002V6.34139C5.29998 6.17571 5.43429 6.04139 5.59998 6.04139H10.4Z"
        fill="#628099"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
