/**
 * @file MarkDown markdown
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'markdown',
  false,
  (props: ISvgIconProps) => (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M13.5265 4.00024H11.5151V8.55859H9.04089L12.5205 12.4396L16.0001 8.55859H13.5265V4.00024Z"
        fill="#3ADEAC"
      />
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M6.57023 4.00024H8.58165V12.4396H6.57023V7.12947L6.04568 7.75459L4.49563 9.62392L3.42792 8.3415L2.41145 7.13012V12.4399H0.400024V4.00061H2.41068L2.41099 4.00035L2.41121 4.00061H2.41145V4.0009L4.49057 6.47869L6.57023 4.00024Z"
        fill="#3ADEAC"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
