/**
 * @file Yaml yaml
 * @author Auto Generated by IconPark
 */

/* tslint:disable: max-line-length */
/* eslint-disable max-len */
import React from 'react';
import { ISvgIconProps, IconWrapper } from '../runtime';

export default IconWrapper(
  'yaml',
  false,
  (props: ISvgIconProps) => (
    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
      <path
        fillRule="evenodd"
        clipRule="evenodd"
        d="M10.1821 2.51831H13.3465L5.6645 14.0183H2.50012L6.34112 8.26831L2.50012 2.51831H5.6645L7.92332 5.89975L10.1821 2.51831Z"
        fill="#FFA841"
      />
    </svg>
  ),
  (props: ISvgIconProps) => `
`,
);
