{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}

{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fedlearner-web-console-v2.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressPrefix := .Values.ingress.ingressPrefix -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fedlearner-web-console-v2.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ printf "%s.%s" $ingressPrefix (.domainName | required "http domain name is required") | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
      {{- end }}
  {{- end }}

{{- end }}
{{- end }}
