apiVersion: v1
kind: Service
metadata:
  name: {{ include "fedlearner-web-console.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fedlearner-web-console.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1989
      protocol: TCP
      name: http
  selector:
    {{- include "fedlearner-web-console.selectorLabels" . | nindent 4 }}
