apiVersion: v1
appVersion: v2.4.0
description: A Fluentd Elasticsearch Helm chart for Kubernetes.
home: https://www.fluentd.org/
icon: https://raw.githubusercontent.com/fluent/fluentd-docs/master/public/logo/Fluentd_square.png
maintainers:
- email: pete.brown@powerhrg.com
  name: rendhalver
- email: maxime@root314.com
  name: miouge1
- email: hfernandez@mesosphere.com
  name: hectorj2f
name: fluentd
sources:
- https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch/fluentd-es-image
- https://quay.io/repository/coreos/fluentd-kubernetes
- https://github.com/coreos/fluentd-kubernetes-daemonset
- https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html
version: 2.2.0
