apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fedlearner-operator
  name: fedlearner-operator
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fedlearner-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fedlearner-operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
            - --port=8100
            - --namespace={{ .Release.Namespace }}
            - --leader-election=true
            - --leader-election-lock-namespace={{ .Release.Namespace }}
            - --resync-interval=5
          {{- range $key, $value := .Values.extraArgs }}
            {{- if $value }}
            - --{{ $key }}={{ $value }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
          command:
            - /app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: fedlearner-operator
          ports:
            - containerPort: 8100
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      serviceAccountName: fedlearner-operator
