{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}

{{- if .Values.ingress.enabled -}}
{{- $ingressSuffix := index .Values.extraArgs "ingress-extra-host-suffix" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fedlearner-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fedlearner-operator.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ printf "%s%s" (.Values.ingress.host | required "host cannot be null") $ingressSuffix | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fedlearner-operator
                port:
                  number: 8100
{{- end }}

{{- end }}
