{{- if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion -}}

{{- if .Values.ingress.enabled -}}
{{- $ingressSuffix := index .Values.extraArgs "ingress-extra-host-suffix" -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: fedlearner-operator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fedlearner-operator.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - host: {{ printf "%s%s" (.Values.ingress.host | required "host cannot be null") $ingressSuffix | quote }}
      http:
        paths:
          - backend:
              serviceName: fedlearner-operator
              servicePort: 8100
{{- end }}

{{- end }}

