apiVersion: v1
kind: Service
metadata:
  name: fedlearner-operator
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: fedlearner-operator
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
