apiVersion: v1
appVersion: 6.7.0
description: Kibana is an open source data visualization plugin for Elasticsearch
engine: gotpl
home: https://www.elastic.co/products/kibana
icon: https://raw.githubusercontent.com/elastic/kibana/master/src/ui/public/icons/kibana-color.svg
keywords:
- elasticsearch
- kibana
maintainers:
- email: casey@monax.io
  name: compleatang
- email: monotek23@gmail.com
  name: monotek
name: kibana
sources:
- https://github.com/elastic/kibana
version: 3.2.4
