apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-fedlearner-default
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.nfs.capacity }}
  mountOptions:
    - vers=3
    - nolock,tcp,noresvport
  nfs:
    path: {{ .Values.nfs.path }}
    server: {{ .Values.nfs.server }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
