apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-fedlearner-default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.nfs.capacity }}
  volumeName: pv-fedlearner-default
  storageClassName: nfs
