/* Copyright 2020 The FedLearner Authors. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/bytedance/fedlearner/deploy/kubernetes_operator/pkg/apis/fedlearner.k8s.io/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// FLAppLister helps list FLApps.
type FLAppLister interface {
	// List lists all FLApps in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.FLApp, err error)
	// FLApps returns an object that can list and get FLApps.
	FLApps(namespace string) FLAppNamespaceLister
	FLAppListerExpansion
}

// fLAppLister implements the FLAppLister interface.
type fLAppLister struct {
	indexer cache.Indexer
}

// NewFLAppLister returns a new FLAppLister.
func NewFLAppLister(indexer cache.Indexer) FLAppLister {
	return &fLAppLister{indexer: indexer}
}

// List lists all FLApps in the indexer.
func (s *fLAppLister) List(selector labels.Selector) (ret []*v1alpha1.FLApp, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FLApp))
	})
	return ret, err
}

// FLApps returns an object that can list and get FLApps.
func (s *fLAppLister) FLApps(namespace string) FLAppNamespaceLister {
	return fLAppNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// FLAppNamespaceLister helps list and get FLApps.
type FLAppNamespaceLister interface {
	// List lists all FLApps in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.FLApp, err error)
	// Get retrieves the FLApp from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.FLApp, error)
	FLAppNamespaceListerExpansion
}

// fLAppNamespaceLister implements the FLAppNamespaceLister
// interface.
type fLAppNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all FLApps in the indexer for a given namespace.
func (s fLAppNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.FLApp, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.FLApp))
	})
	return ret, err
}

// Get retrieves the FLApp from the indexer for a given namespace and name.
func (s fLAppNamespaceLister) Get(name string) (*v1alpha1.FLApp, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("flapp"), name)
	}
	return obj.(*v1alpha1.FLApp), nil
}
