/* istanbul ignore file */

/* eslint-disable */
/**
 * WARNING: This file is auto-generated
 * DO NOT modify it directly, src/styles/variables/bioland.less is the file you should go
 */
const defaultTheme = {
  red1: '#ffece8',
  red2: '#fdcdc5',
  red5: '#f76560',
  red6: '#f53f3f',
  orange6: '#ff7d00',
  green6: '#00b42a',
  blue4: '#7bc0fc',
  blue6: '#3491fa',
  gray1: '#f7f8fa',
  gray2: '#f2f3f5',
  gray3: '#e5e6eb',
  gray4: '#c9cdd4',
  gray6: '#86909c',
  gray8: '#4e5969',
  gray9: '#272e3b',
  gray10: '#1d2129',
  newPrimaryDefault: '#4450dc',
  newPrimaryHover: '#6171e3',
  newPrimaryActive: '#2b32b8',
  newPrimaryDisable: '#a1b0f1',
  newPrimaryHoverGray: '#c4cff8',
  primaryColor: '#4450dc',
  infoColor: '#4450dc',
  successColor: '#00b42a',
  processingColor: '#3491fa',
  errorColor: '#f53f3f',
  errorColorLight: '#ffece8',
  highlightColor: '#f76560',
  warningColor: '#ff7d00',
  normalColor: '#272e3b',
  textColor: '#4e5969',
  textColorStrong: '#1d2129',
  textColorStrongSecondary: '#4e5969',
  textColorSecondary: '#86909c',
  textColorDisabled: '#c9cdd4',
  textColorInverse: 'white',
  componentBackgroundColorGray: '#f2f3f5',
  backgroundColor: '#f7f8fa',
  backgroundColorGray: '#e5e6eb',
  backgroundColorError: '#ffece8',
  backgroundColorErrorHover: '#fdcdc5',
  lineColor: '#e5e8ef',
  headerBackground: '#4450dc',
  headerBorderBottomWidth: '0',
  headerLogoHeight: '42px',
  headerProjectColor: '#fff',
  headerPaddingLeft: '0',
  headerPaddingRight: '30px',
  commonTiming: 'cubic-bezier(0.4, 0, 0.2, 1)',
  fontFamily: "'nunito_for_arco', 'Helvetica Neue', Helvetica, 'PingFang SC', 'Hiragino Sans GB',  'Microsoft YaHei', '微软雅黑', Arial, sans-serif",
  headerHeight: '60px',
  pageHeaderHeight: '44px',
  contentOuterPadding: '16px',
  contentMinHeight: 'calc(100vh - 60px - 16px * 2)',
  textFontSizePrimary: '12px',
  zIndexLessThanModal: '999',
}

export default defaultTheme
