name: Build Web Console

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Coverage Testing and Assets Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Build and test using Node.js@${{ matrix.node-version }}
      run: |
        cd ./web_console
        npm ci
        npm run cov
        npm run build
