name: Release Fedlearner APIServer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Short Commit Sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: fedlearner
          password: "${{ secrets.DOCKER_REGISTRY }}"
          image_name: fedlearner/fedlearner-apiserver
          image_tag: ${{ steps.vars.outputs.sha_short }}
          context: ./deploy/kubernetes_operator
          build_extra_args: --build-arg=WHAT=cmd/apiserver/main.go
