name: Web Consolve V2 API CI

on:
  pull_request:
    paths:
      - 'web_console_v2/**'
      - '.github/**'
  push:
    paths:
      - 'web_console_v2/**'
      - '.github/**'

jobs:
  test-api:
    name: API tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        working-directory: web_console_v2/api
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run test
        working-directory: web_console_v2
        run: make api-test
